// apps/pos-app/src/app/pages/pos/payment-dialog.component.ts
import { Component, Inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  MAT_DIALOG_DATA,
  MatDialogModule,
  MatDialogRef,
} from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTabsModule } from '@angular/material/tabs';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';

export interface PaymentDialogData {
  total: number;
  itemCount: number;
}

export interface PaymentDialogResult {
  method: 'cash' | 'card';
  amountPaid: number;
  change: number;
}

@Component({
  selector: 'bake-app-payment-dialog',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatDialogModule,
    MatButtonModule,
    MatIconModule,
    MatTabsModule,
    MatFormFieldModule,
    MatInputModule,
  ],
  template: `
    <div class="payment-dialog">
      <div class="dialog-header">
        <h2>Payment</h2>
        <button mat-icon-button mat-dialog-close>
          <mat-icon>close</mat-icon>
        </button>
      </div>

      <div class="total-display">
        <span class="total-label">Total Due</span>
        <span class="total-amount">{{ data.total | currency:'USD':'symbol':'1.0-0' }}</span>
      </div>

      <mat-tab-group
        class="payment-tabs"
        [(selectedIndex)]="selectedTab"
        animationDuration="200ms"
      >
        <!-- Cash Tab -->
        <mat-tab>
          <ng-template mat-tab-label>
            <mat-icon>payments</mat-icon>
            <span class="tab-label-text">Cash</span>
          </ng-template>

          <div class="tab-content">
            <mat-form-field appearance="outline" class="amount-field">
              <mat-label>Amount received</mat-label>
              <input
                matInput
                type="number"
                [(ngModel)]="cashAmount"
                (ngModelChange)="calculateChange()"
                placeholder="0"
                min="0"
                class="amount-input"
              />
              <span matPrefix class="currency-prefix">$</span>
            </mat-form-field>

            <div class="quick-amounts">
              <button
                mat-stroked-button
                class="quick-btn"
                (click)="setCashAmount(data.total)"
              >
                Exact
              </button>
              <button
                mat-stroked-button
                class="quick-btn"
                (click)="addCashAmount(500)"
              >
                +$500
              </button>
              <button
                mat-stroked-button
                class="quick-btn"
                (click)="addCashAmount(1000)"
              >
                +$1,000
              </button>
              <button
                mat-stroked-button
                class="quick-btn"
                (click)="addCashAmount(2000)"
              >
                +$2,000
              </button>
              <button
                mat-stroked-button
                class="quick-btn"
                (click)="addCashAmount(5000)"
              >
                +$5,000
              </button>
              <button
                mat-stroked-button
                class="quick-btn"
                (click)="setCashAmount(roundUp(data.total, 1000))"
              >
                {{ roundUp(data.total, 1000) | currency:'USD':'symbol':'1.0-0' }}
              </button>
            </div>

            <div class="change-display" *ngIf="cashAmount >= data.total">
              <span class="change-label">Change</span>
              <span class="change-amount">{{ change | currency:'USD':'symbol':'1.0-0' }}</span>
            </div>

            <div class="insufficient" *ngIf="cashAmount > 0 && cashAmount < data.total">
              <mat-icon>warning</mat-icon>
              Insufficient amount
            </div>

            <button
              mat-flat-button
              class="confirm-btn cash-btn"
              [disabled]="cashAmount < data.total"
              (click)="confirmPayment('cash')"
            >
              <mat-icon>check_circle</mat-icon>
              Complete Cash Payment
            </button>
          </div>
        </mat-tab>

        <!-- Card Tab -->
        <mat-tab>
          <ng-template mat-tab-label>
            <mat-icon>credit_card</mat-icon>
            <span class="tab-label-text">Card</span>
          </ng-template>

          <div class="tab-content card-tab">
            <div class="card-processing">
              <mat-icon class="card-icon">contactless</mat-icon>
              <p class="card-instruction">
                Tap, insert, or swipe card to process payment
              </p>
              <button
                mat-flat-button
                class="confirm-btn card-btn"
                (click)="processCard()"
              >
                <mat-icon>credit_card</mat-icon>
                Process Card Payment
              </button>
            </div>
          </div>
        </mat-tab>
      </mat-tab-group>
    </div>
  `,
  styles: [
    `
      .payment-dialog {
        min-width: 400px;
      }

      .dialog-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 16px;
      }

      .dialog-header h2 {
        margin: 0;
        font-size: 20px;
        font-weight: 600;
        color: #3e2723;
      }

      .total-display {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 16px 20px;
        background-color: #faf3e8;
        border-radius: 10px;
        margin-bottom: 20px;
      }

      .total-label {
        font-size: 16px;
        font-weight: 500;
        color: #5d4037;
      }

      .total-amount {
        font-size: 28px;
        font-weight: 700;
        color: #8b4513;
        font-family: 'JetBrains Mono', monospace;
      }

      .tab-label-text {
        margin-left: 6px;
      }

      .tab-content {
        padding: 20px 0;
      }

      .amount-field {
        width: 100%;
      }

      .amount-input {
        font-size: 20px;
        font-family: 'JetBrains Mono', monospace;
        font-weight: 600;
      }

      .currency-prefix {
        font-size: 18px;
        font-weight: 600;
        color: #8b4513;
        margin-right: 4px;
      }

      .quick-amounts {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 8px;
        margin-bottom: 20px;
      }

      .quick-btn {
        font-family: 'JetBrains Mono', monospace;
        font-weight: 500;
        font-size: 13px;
        border-color: #d4a574;
        color: #5d4037;
      }

      .quick-btn:hover {
        background-color: #faf3e8;
      }

      .change-display {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 14px 20px;
        background-color: #e8f5e9;
        border-radius: 10px;
        margin-bottom: 20px;
      }

      .change-label {
        font-size: 15px;
        font-weight: 500;
        color: #2e7d32;
      }

      .change-amount {
        font-size: 24px;
        font-weight: 700;
        color: #2e7d32;
        font-family: 'JetBrains Mono', monospace;
      }

      .insufficient {
        display: flex;
        align-items: center;
        gap: 8px;
        color: #c62828;
        font-size: 13px;
        padding: 10px 16px;
        background-color: #ffebee;
        border-radius: 8px;
        margin-bottom: 20px;
      }

      .insufficient mat-icon {
        font-size: 18px;
        width: 18px;
        height: 18px;
      }

      .confirm-btn {
        width: 100%;
        height: 48px;
        font-size: 15px;
        font-weight: 600;
        border-radius: 8px;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 8px;
      }

      .cash-btn {
        background-color: #2e7d32 !important;
        color: #fff !important;
      }

      .cash-btn:disabled {
        opacity: 0.5;
      }

      .card-btn {
        background-color: #1565c0 !important;
        color: #fff !important;
      }

      .card-tab {
        text-align: center;
      }

      .card-processing {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 16px;
        padding: 24px 0;
      }

      .card-icon {
        font-size: 64px;
        width: 64px;
        height: 64px;
        color: #1565c0;
      }

      .card-instruction {
        font-size: 15px;
        color: #546e7a;
        margin: 0;
      }

      .processing-text {
        font-size: 16px;
        font-weight: 500;
        color: #3e2723;
        margin: 0;
      }

      .processing-subtext {
        font-size: 13px;
        color: #8d6e63;
        margin: 0;
      }
    `,
  ],
})
export class PaymentDialogComponent {
  cashAmount = 0;
  change = 0;
  selectedTab = 0;

  constructor(
    public dialogRef: MatDialogRef<PaymentDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: PaymentDialogData
  ) {}

  calculateChange(): void {
    this.change = Math.max(0, this.cashAmount - this.data.total);
  }

  setCashAmount(amount: number): void {
    this.cashAmount = amount;
    this.calculateChange();
  }

  addCashAmount(amount: number): void {
    this.cashAmount += amount;
    this.calculateChange();
  }

  roundUp(value: number, step: number): number {
    return Math.ceil(value / step) * step;
  }

  confirmPayment(method: 'cash' | 'card'): void {
    const result: PaymentDialogResult = {
      method,
      amountPaid: method === 'cash' ? this.cashAmount : this.data.total,
      change: method === 'cash' ? this.change : 0,
    };
    this.dialogRef.close(result);
  }

  processCard(): void {
    this.confirmPayment('card');
  }
}

// apps/pos-app/src/components/payment-dialog.tsx
import { useState } from 'react';
import {
  X,
  Banknote,
  CreditCard,
  Nfc,
  CheckCircle2,
  AlertTriangle,
} from 'lucide-react';
import { CurrencyDisplay } from '@bake-app/react/ui';

export interface PaymentResult {
  method: 'cash' | 'card';
  amountPaid: number;
  change: number;
}

interface PaymentDialogProps {
  open: boolean;
  onClose: () => void;
  total: number;
  itemCount: number;
  onConfirm: (result: PaymentResult) => void;
}

type PaymentTab = 'cash' | 'card';

export function PaymentDialog({
  open,
  onClose,
  total,
  itemCount,
  onConfirm,
}: PaymentDialogProps) {
  const [tab, setTab] = useState<PaymentTab>('cash');
  const [cashAmount, setCashAmount] = useState('');

  if (!open) return null;

  const numericAmount = parseFloat(cashAmount) || 0;
  const change = numericAmount - total;
  const isSufficient = numericAmount >= total;
  const isInsufficient = numericAmount > 0 && numericAmount < total;

  const roundUp = (n: number): number => {
    if (n <= 100) return Math.ceil(n / 10) * 10;
    if (n <= 1000) return Math.ceil(n / 100) * 100;
    return Math.ceil(n / 1000) * 1000;
  };

  const quickAmounts = [
    { label: 'Exact', value: total },
    { label: '+$500', value: numericAmount + 500 },
    { label: '+$1000', value: numericAmount + 1000 },
    { label: '+$2000', value: numericAmount + 2000 },
    { label: '+$5000', value: numericAmount + 5000 },
    { label: `Round up ($${roundUp(total).toLocaleString()})`, value: roundUp(total) },
  ];

  function handleCashConfirm() {
    if (!isSufficient) return;
    onConfirm({ method: 'cash', amountPaid: numericAmount, change });
    resetAndClose();
  }

  function handleCardConfirm() {
    onConfirm({ method: 'card', amountPaid: total, change: 0 });
    resetAndClose();
  }

  function resetAndClose() {
    setCashAmount('');
    setTab('cash');
  }

  function handleOverlayClick(e: React.MouseEvent) {
    if (e.target === e.currentTarget) {
      onClose();
    }
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"
      onClick={handleOverlayClick}
    >
      <div className="relative w-full max-w-[480px] mx-4 bg-white rounded-2xl shadow-2xl overflow-hidden">
        {/* Close button */}
        <button
          type="button"
          onClick={onClose}
          className="absolute right-4 top-4 z-10 rounded-full p-1 text-[#5d4037] hover:bg-[#faf3e8] transition-colors border-none bg-transparent cursor-pointer"
        >
          <X size={20} />
        </button>

        {/* Total due header */}
        <div className="bg-[#faf3e8] px-6 py-5 text-center">
          <p className="text-sm text-[#5d4037] mb-1">Total Due ({itemCount} items)</p>
          <p className="text-3xl font-bold font-mono text-[#3e2723]">
            ${total.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </p>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-200">
          <button
            type="button"
            onClick={() => setTab('cash')}
            className={`flex-1 flex items-center justify-center gap-2 py-3 text-sm font-semibold border-none cursor-pointer transition-colors ${
              tab === 'cash'
                ? 'text-[#8b4513] border-b-2 border-[#8b4513] bg-white'
                : 'text-gray-500 bg-gray-50 hover:text-[#5d4037]'
            }`}
          >
            <Banknote size={18} />
            Cash
          </button>
          <button
            type="button"
            onClick={() => setTab('card')}
            className={`flex-1 flex items-center justify-center gap-2 py-3 text-sm font-semibold border-none cursor-pointer transition-colors ${
              tab === 'card'
                ? 'text-[#1565c0] border-b-2 border-[#1565c0] bg-white'
                : 'text-gray-500 bg-gray-50 hover:text-[#5d4037]'
            }`}
          >
            <CreditCard size={18} />
            Card
          </button>
        </div>

        {/* Tab content */}
        <div className="p-6">
          {tab === 'cash' ? (
            <div className="space-y-4">
              {/* Amount input */}
              <div>
                <label className="block text-sm font-medium text-[#5d4037] mb-1.5">
                  Amount Received
                </label>
                <div className="relative">
                  <span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl font-mono text-[#5d4037]">
                    $
                  </span>
                  <input
                    type="number"
                    value={cashAmount}
                    onChange={(e) => setCashAmount(e.target.value)}
                    placeholder="0.00"
                    min="0"
                    step="0.01"
                    className="w-full pl-10 pr-4 py-4 text-2xl font-mono font-semibold text-[#3e2723]
                      border border-[#d7ccc8] rounded-xl bg-white
                      focus:outline-none focus:border-[#8b4513] focus:ring-2 focus:ring-[#8b4513]/20
                      transition-colors placeholder-gray-300"
                  />
                </div>
              </div>

              {/* Quick amount buttons */}
              <div className="grid grid-cols-3 gap-2">
                {quickAmounts.map((qa) => (
                  <button
                    key={qa.label}
                    type="button"
                    onClick={() => setCashAmount(qa.value.toFixed(2))}
                    className="py-2 px-3 text-xs font-medium text-[#5d4037] bg-[#faf3e8]
                      rounded-lg border border-[#8b4513]/10 hover:bg-[#f5e6d0]
                      transition-colors cursor-pointer"
                  >
                    {qa.label}
                  </button>
                ))}
              </div>

              {/* Change display */}
              {isSufficient && (
                <div className="flex items-center gap-3 p-4 bg-green-50 border border-green-200 rounded-xl">
                  <CheckCircle2 className="text-green-600 shrink-0" size={24} />
                  <div>
                    <p className="text-sm font-medium text-green-800">Change</p>
                    <p className="text-xl font-mono font-bold text-green-700">
                      ${change.toLocaleString('en-US', {
                        minimumFractionDigits: 2,
                        maximumFractionDigits: 2,
                      })}
                    </p>
                  </div>
                </div>
              )}

              {/* Insufficient warning */}
              {isInsufficient && (
                <div className="flex items-center gap-3 p-4 bg-red-50 border border-red-200 rounded-xl">
                  <AlertTriangle className="text-red-600 shrink-0" size={24} />
                  <div>
                    <p className="text-sm font-medium text-red-800">Insufficient amount</p>
                    <p className="text-sm text-red-600">
                      Need ${(total - numericAmount).toLocaleString('en-US', {
                        minimumFractionDigits: 2,
                        maximumFractionDigits: 2,
                      })} more
                    </p>
                  </div>
                </div>
              )}

              {/* Confirm button */}
              <button
                type="button"
                onClick={handleCashConfirm}
                disabled={!isSufficient}
                className="w-full py-3.5 bg-green-600 text-white text-base font-semibold rounded-xl
                  border-none cursor-pointer hover:bg-green-700 transition-colors
                  disabled:opacity-50 disabled:cursor-not-allowed
                  flex items-center justify-center gap-2"
              >
                <Banknote size={20} />
                Complete Cash Payment
              </button>
            </div>
          ) : (
            <div className="flex flex-col items-center gap-6 py-6">
              {/* Card icon */}
              <div className="w-24 h-24 rounded-full bg-blue-50 flex items-center justify-center">
                <Nfc className="text-[#1565c0]" size={48} />
              </div>

              <div className="text-center">
                <p className="text-lg font-semibold text-[#3e2723] mb-1">
                  Ready for card payment
                </p>
                <p className="text-sm text-gray-500">
                  Tap, insert, or swipe card
                </p>
              </div>

              <div className="text-center">
                <p className="text-sm text-gray-500">Amount</p>
                <CurrencyDisplay amount={total} size="lg" />
              </div>

              {/* Confirm button */}
              <button
                type="button"
                onClick={handleCardConfirm}
                className="w-full py-3.5 bg-[#1565c0] text-white text-base font-semibold rounded-xl
                  border-none cursor-pointer hover:bg-[#0d47a1] transition-colors
                  flex items-center justify-center gap-2"
              >
                <CreditCard size={20} />
                Process Card Payment
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
