// apps/kitchen-screen/src/app/pages/production/production.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { ApiClientService } from '@bake-app/api-client';
import { ProductionPlan, ProductionTask } from '@bake-app/shared-types';

interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

type ProductionStatus = 'Scheduled' | 'In Progress' | 'Completed' | 'Delayed';

interface ProductionItem {
  id: string;
  time: string;
  recipe: string;
  plannedQty: number;
  actualQty: number;
  status: ProductionStatus;
  progress: number;
  notes?: string;
}

@Component({
  selector: 'bake-app-production',
  standalone: true,
  imports: [
    CommonModule,
    MatIconModule,
    MatButtonModule,
  ],
  template: `
    <div class="production-container">
      <div class="production-header">
        <div class="header-left">
          <h1 class="page-title">Daily Production Schedule</h1>
          <span class="page-date">{{ today }}</span>
        </div>
        <div class="header-stats">
          <div class="stat-pill stat-pill--completed">
            <mat-icon>check_circle</mat-icon>
            <span class="stat-value">{{ completedCount }}</span>
            <span class="stat-label">Done</span>
          </div>
          <div class="stat-pill stat-pill--progress">
            <mat-icon>autorenew</mat-icon>
            <span class="stat-value">{{ inProgressCount }}</span>
            <span class="stat-label">Active</span>
          </div>
          <div class="stat-pill stat-pill--scheduled">
            <mat-icon>schedule</mat-icon>
            <span class="stat-value">{{ scheduledCount }}</span>
            <span class="stat-label">Upcoming</span>
          </div>
          <div class="stat-pill stat-pill--delayed" *ngIf="delayedCount > 0">
            <mat-icon>warning</mat-icon>
            <span class="stat-value">{{ delayedCount }}</span>
            <span class="stat-label">Delayed</span>
          </div>
        </div>
      </div>

      <div class="table-wrapper">
        <table class="production-table">
          <thead>
            <tr>
              <th class="col-time">Time</th>
              <th class="col-recipe">Recipe</th>
              <th class="col-qty">Planned</th>
              <th class="col-qty">Actual</th>
              <th class="col-status">Status</th>
              <th class="col-progress">Progress</th>
              <th class="col-notes">Notes</th>
            </tr>
          </thead>
          <tbody>
            <tr
              *ngFor="let item of productionItems"
              class="table-row"
              [ngClass]="'row--' + item.status.toLowerCase().replace(' ', '-')"
            >
              <td class="col-time">
                <span class="time-value">{{ item.time }}</span>
              </td>
              <td class="col-recipe">
                <span class="recipe-name">{{ item.recipe }}</span>
              </td>
              <td class="col-qty">
                <span class="qty-value">{{ item.plannedQty }}</span>
              </td>
              <td class="col-qty">
                <span
                  class="qty-value"
                  [class.qty-behind]="item.actualQty < item.plannedQty && (item.status === 'Completed' || item.status === 'Delayed')"
                  [class.qty-ahead]="item.actualQty >= item.plannedQty && item.status === 'Completed'"
                >
                  {{ item.actualQty }}
                </span>
              </td>
              <td class="col-status">
                <span
                  class="status-badge"
                  [ngClass]="'badge--' + item.status.toLowerCase().replace(' ', '-')"
                >
                  {{ item.status }}
                </span>
              </td>
              <td class="col-progress">
                <div class="progress-container">
                  <div class="progress-track">
                    <div
                      class="progress-fill"
                      [style.width.%]="item.progress"
                      [ngClass]="'fill--' + item.status.toLowerCase().replace(' ', '-')"
                    ></div>
                  </div>
                  <span class="progress-text">{{ item.progress }}%</span>
                </div>
              </td>
              <td class="col-notes">
                <span class="notes-text">{{ item.notes || '-' }}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
      height: 100%;
      overflow-y: auto;
    }

    .production-container {
      padding: 24px;
      min-height: 100%;
    }

    .production-header {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      margin-bottom: 24px;
    }

    .header-left {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .page-title {
      font-size: 26px;
      font-weight: 700;
      color: #FFFFFF;
      margin: 0;
    }

    .page-date {
      font-size: 15px;
      color: rgba(255, 255, 255, 0.45);
    }

    .header-stats {
      display: flex;
      gap: 12px;
    }

    .stat-pill {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 10px 18px;
      border-radius: 10px;
      font-size: 14px;
      font-weight: 500;
    }

    .stat-pill mat-icon {
      font-size: 20px;
      width: 20px;
      height: 20px;
    }

    .stat-value {
      font-family: 'JetBrains Mono', monospace;
      font-size: 20px;
      font-weight: 700;
    }

    .stat-label {
      font-size: 13px;
      opacity: 0.7;
    }

    .stat-pill--completed {
      background-color: rgba(129, 199, 132, 0.12);
      color: #81C784;
      border: 1px solid rgba(129, 199, 132, 0.25);
    }

    .stat-pill--progress {
      background-color: rgba(255, 183, 77, 0.12);
      color: #FFB74D;
      border: 1px solid rgba(255, 183, 77, 0.25);
    }

    .stat-pill--scheduled {
      background-color: rgba(79, 195, 247, 0.12);
      color: #4FC3F7;
      border: 1px solid rgba(79, 195, 247, 0.25);
    }

    .stat-pill--delayed {
      background-color: rgba(239, 83, 80, 0.12);
      color: #EF5350;
      border: 1px solid rgba(239, 83, 80, 0.25);
    }

    /* Table */
    .table-wrapper {
      background-color: #16213E;
      border-radius: 14px;
      overflow: hidden;
      border: 1px solid rgba(255, 255, 255, 0.06);
    }

    .production-table {
      width: 100%;
      border-collapse: collapse;
    }

    .production-table thead {
      background-color: rgba(255, 255, 255, 0.04);
    }

    .production-table th {
      padding: 18px 20px;
      text-align: left;
      font-size: 13px;
      font-weight: 600;
      color: rgba(255, 255, 255, 0.45);
      text-transform: uppercase;
      letter-spacing: 1px;
      border-bottom: 1px solid rgba(255, 255, 255, 0.08);
    }

    .production-table td {
      padding: 20px 20px;
      font-size: 17px;
      color: rgba(255, 255, 255, 0.85);
      border-bottom: 1px solid rgba(255, 255, 255, 0.04);
    }

    .table-row {
      transition: background-color 0.15s ease;
    }

    .table-row:hover {
      background-color: rgba(255, 255, 255, 0.03);
    }

    .table-row:last-child td {
      border-bottom: none;
    }

    .row--delayed {
      background-color: rgba(239, 83, 80, 0.04);
    }

    .col-time {
      width: 100px;
    }

    .col-recipe {
      width: auto;
    }

    .col-qty {
      width: 90px;
      text-align: center;
    }

    .col-status {
      width: 140px;
    }

    .col-progress {
      width: 180px;
    }

    .col-notes {
      width: 200px;
    }

    .time-value {
      font-family: 'JetBrains Mono', monospace;
      font-size: 18px;
      font-weight: 600;
      color: #FFFFFF;
    }

    .recipe-name {
      font-size: 17px;
      font-weight: 600;
      color: #FFFFFF;
    }

    .qty-value {
      font-family: 'JetBrains Mono', monospace;
      font-size: 18px;
      font-weight: 600;
    }

    .qty-behind {
      color: #EF5350;
    }

    .qty-ahead {
      color: #81C784;
    }

    /* Status badges */
    .status-badge {
      display: inline-block;
      padding: 6px 14px;
      border-radius: 8px;
      font-size: 13px;
      font-weight: 700;
      letter-spacing: 0.5px;
      text-transform: uppercase;
    }

    .badge--scheduled {
      background-color: rgba(79, 195, 247, 0.15);
      color: #4FC3F7;
    }

    .badge--in-progress {
      background-color: rgba(255, 183, 77, 0.15);
      color: #FFB74D;
    }

    .badge--completed {
      background-color: rgba(129, 199, 132, 0.15);
      color: #81C784;
    }

    .badge--delayed {
      background-color: rgba(239, 83, 80, 0.15);
      color: #EF5350;
    }

    /* Progress */
    .progress-container {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .progress-track {
      flex: 1;
      height: 8px;
      background-color: rgba(255, 255, 255, 0.08);
      border-radius: 4px;
      overflow: hidden;
    }

    .progress-fill {
      height: 100%;
      border-radius: 4px;
      transition: width 0.3s ease;
    }

    .fill--scheduled {
      background-color: #4FC3F7;
    }

    .fill--in-progress {
      background: linear-gradient(90deg, #FFB74D, #FF9800);
    }

    .fill--completed {
      background-color: #81C784;
    }

    .fill--delayed {
      background-color: #EF5350;
    }

    .progress-text {
      font-family: 'JetBrains Mono', monospace;
      font-size: 14px;
      font-weight: 600;
      color: rgba(255, 255, 255, 0.5);
      min-width: 40px;
      text-align: right;
    }

    .notes-text {
      font-size: 14px;
      color: rgba(255, 255, 255, 0.4);
    }
  `],
})
export class ProductionComponent implements OnInit {
  productionItems: ProductionItem[] = [];

  constructor(private apiClient: ApiClientService) {}

  ngOnInit(): void {
    this.loadProduction();
  }

  private loadProduction(): void {
    const todayStr = new Date().toISOString().split('T')[0];
    this.apiClient
      .get<ProductionPlan[]>(`/v1/production/plans?date=${todayStr}`)
      .subscribe({
        next: (plans) => {
          this.productionItems = [];
          for (const plan of plans) {
            for (const task of plan.tasks) {
              this.productionItems.push(this.mapTask(task));
            }
          }
        },
        error: () => {
          this.productionItems = [];
        },
      });
  }

  private mapTask(task: ProductionTask): ProductionItem {
    const statusMap: Record<string, ProductionStatus> = {
      pending: 'Scheduled',
      in_progress: 'In Progress',
      completed: 'Completed',
      delayed: 'Delayed',
    };
    const planned = task.plannedQuantity;
    const actual = task.actualYield || 0;
    const progress = planned > 0 ? Math.round((actual / planned) * 100) : 0;
    const time = task.scheduledStart
      ? new Date(task.scheduledStart).toLocaleTimeString('en-US', {
          hour: '2-digit',
          minute: '2-digit',
          hour12: false,
        })
      : '--:--';
    return {
      id: task.id,
      time,
      recipe: task.recipeName || 'Recipe',
      plannedQty: planned,
      actualQty: actual,
      status: statusMap[task.status] || 'Scheduled',
      progress: Math.min(progress, 100),
    };
  }

  get today(): string {
    return new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  get completedCount(): number {
    return this.productionItems.filter(i => i.status === 'Completed').length;
  }

  get inProgressCount(): number {
    return this.productionItems.filter(i => i.status === 'In Progress').length;
  }

  get scheduledCount(): number {
    return this.productionItems.filter(i => i.status === 'Scheduled').length;
  }

  get delayedCount(): number {
    return this.productionItems.filter(i => i.status === 'Delayed').length;
  }
}

// apps/kitchen-screen/src/pages/production.tsx
import { useMemo } from 'react';
import { useNavigate } from 'react-router';
import { toast } from 'sonner';
import {
  useProductionPlans,
  useUpdateTaskStatus,
} from '@bake-app/react/api-client';
import type { ProductionTask } from '@bake-app/shared-types';
import {
  ArrowLeft,
  Clock,
  PlayCircle,
  CheckCircle2,
  AlertTriangle,
  Hourglass,
} from 'lucide-react';

const STATUS_ORDER = ['pending', 'in_progress', 'completed', 'delayed'] as const;

const STATUS_CONFIG: Record<
  string,
  { label: string; icon: typeof Clock; color: string; bg: string }
> = {
  pending: {
    label: 'Scheduled',
    icon: Hourglass,
    color: 'text-[#4FC3F7]',
    bg: 'bg-[#4FC3F7]/10',
  },
  in_progress: {
    label: 'In Progress',
    icon: PlayCircle,
    color: 'text-[#FFB74D]',
    bg: 'bg-[#FFB74D]/10',
  },
  completed: {
    label: 'Completed',
    icon: CheckCircle2,
    color: 'text-[#81C784]',
    bg: 'bg-[#81C784]/10',
  },
  delayed: {
    label: 'Delayed',
    icon: AlertTriangle,
    color: 'text-red-400',
    bg: 'bg-red-400/10',
  },
};

export function ProductionPage() {
  const navigate = useNavigate();
  const today = new Date().toISOString().split('T')[0];
  const { data: plans, isLoading } = useProductionPlans({ date: today });
  const updateTask = useUpdateTaskStatus();

  // Flatten all tasks from all plans
  const allTasks = useMemo(() => {
    if (!plans) return [];
    const planList = Array.isArray(plans) ? plans : [];
    return planList.flatMap((plan) =>
      (plan.tasks || []).map((task: ProductionTask) => ({
        ...task,
        planDate: plan.date,
        planStatus: plan.status,
      })),
    );
  }, [plans]);

  // Group tasks by status
  const grouped = useMemo(() => {
    const map: Record<string, typeof allTasks> = {};
    for (const s of STATUS_ORDER) {
      map[s] = [];
    }
    for (const task of allTasks) {
      const key = STATUS_ORDER.includes(task.status as (typeof STATUS_ORDER)[number])
        ? task.status
        : 'pending';
      map[key].push(task);
    }
    return map;
  }, [allTasks]);

  function handleStatusChange(taskId: string, newStatus: string) {
    updateTask.mutate(
      { id: taskId, status: newStatus },
      {
        onSuccess: () => toast.success(`Task updated to ${newStatus}`),
        onError: () => toast.error('Failed to update task'),
      },
    );
  }

  if (isLoading) {
    return (
      <div className="flex h-screen items-center justify-center bg-[#0D1B2A]">
        <p className="text-gray-400">Loading production plans...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0D1B2A] p-6">
      <div className="mx-auto max-w-5xl">
        {/* Header */}
        <div className="mb-6 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button
              onClick={() => navigate('/queue')}
              className="flex items-center gap-2 text-sm text-gray-400 transition-colors hover:text-white"
            >
              <ArrowLeft className="h-4 w-4" />
              Queue
            </button>
            <h1 className="text-2xl font-bold text-white">
              Production Tasks
            </h1>
          </div>
          <span className="rounded-lg bg-white/5 px-3 py-1.5 text-sm text-gray-400">
            {today}
          </span>
        </div>

        {allTasks.length === 0 && (
          <div className="flex h-64 items-center justify-center rounded-xl bg-[#16213E] text-gray-500">
            No production tasks for today
          </div>
        )}

        {/* Task groups */}
        {STATUS_ORDER.map((status) => {
          const tasks = grouped[status];
          if (!tasks || tasks.length === 0) return null;
          const config = STATUS_CONFIG[status];
          const Icon = config.icon;

          return (
            <div key={status} className="mb-6">
              <div className={`mb-3 flex items-center gap-2 ${config.color}`}>
                <Icon className="h-5 w-5" />
                <h2 className="text-sm font-bold uppercase tracking-wider">
                  {config.label}
                </h2>
                <span
                  className={`ml-1 flex h-5 w-5 items-center justify-center rounded-full text-xs font-bold ${config.bg} ${config.color}`}
                >
                  {tasks.length}
                </span>
              </div>

              <div className="overflow-hidden rounded-xl bg-[#16213E]">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-white/5 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
                      <th className="px-5 py-3">Recipe</th>
                      <th className="px-5 py-3 text-center">Planned Qty</th>
                      <th className="px-5 py-3 text-center">Actual Yield</th>
                      <th className="px-5 py-3 text-center">Waste</th>
                      <th className="px-5 py-3">Progress</th>
                      <th className="px-5 py-3">Assignee</th>
                      <th className="px-5 py-3 text-right">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {tasks.map((task) => {
                      const yieldPct =
                        task.plannedQuantity > 0 && task.actualYield
                          ? Math.round(
                              (task.actualYield / task.plannedQuantity) * 100,
                            )
                          : 0;

                      return (
                        <tr
                          key={task.id}
                          className="border-b border-white/5 last:border-0"
                        >
                          <td className="px-5 py-4 font-medium text-white">
                            {task.recipeName ?? 'Recipe'}
                          </td>
                          <td className="px-5 py-4 text-center font-mono text-gray-300">
                            {task.plannedQuantity}
                          </td>
                          <td className="px-5 py-4 text-center font-mono text-gray-300">
                            {task.actualYield ?? '-'}
                          </td>
                          <td className="px-5 py-4 text-center font-mono text-gray-300">
                            {task.wasteQuantity > 0 ? (
                              <span className="text-red-400">
                                {task.wasteQuantity}
                              </span>
                            ) : (
                              '-'
                            )}
                          </td>
                          <td className="px-5 py-4">
                            <div className="flex items-center gap-2">
                              <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/5">
                                <div
                                  className="h-full rounded-full transition-all duration-300"
                                  style={{
                                    width: `${Math.min(yieldPct, 100)}%`,
                                    background:
                                      'linear-gradient(90deg, #FFB74D, #FF9800)',
                                  }}
                                />
                              </div>
                              <span className="w-10 text-right text-xs text-gray-500">
                                {yieldPct}%
                              </span>
                            </div>
                          </td>
                          <td className="px-5 py-4 text-sm text-gray-400">
                            {task.assigneeName ?? '-'}
                          </td>
                          <td className="px-5 py-4 text-right">
                            <div className="flex items-center justify-end gap-2">
                              {task.status === 'pending' && (
                                <button
                                  onClick={() =>
                                    handleStatusChange(
                                      task.id,
                                      'in_progress',
                                    )
                                  }
                                  className="rounded-lg bg-[#FFB74D]/20 px-3 py-1.5 text-xs font-semibold text-[#FFB74D] hover:bg-[#FFB74D]/30"
                                >
                                  Start
                                </button>
                              )}
                              {task.status === 'in_progress' && (
                                <button
                                  onClick={() =>
                                    handleStatusChange(
                                      task.id,
                                      'completed',
                                    )
                                  }
                                  className="rounded-lg bg-[#81C784]/20 px-3 py-1.5 text-xs font-semibold text-[#81C784] hover:bg-[#81C784]/30"
                                >
                                  Complete
                                </button>
                              )}
                              {task.status === 'delayed' && (
                                <button
                                  onClick={() =>
                                    handleStatusChange(
                                      task.id,
                                      'in_progress',
                                    )
                                  }
                                  className="rounded-lg bg-[#FFB74D]/20 px-3 py-1.5 text-xs font-semibold text-[#FFB74D] hover:bg-[#FFB74D]/30"
                                >
                                  Resume
                                </button>
                              )}
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
