// apps/kitchen-screen/src/app/pages/queue/queue.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { ApiClientService } from '@bake-app/api-client';
import { AuthService } from '@bake-app/auth';
import { Order } from '@bake-app/shared-types';
import { io, Socket } from 'socket.io-client';

interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

interface OrderItem {
  name: string;
  quantity: number;
  done: boolean;
}

interface KitchenOrder {
  id: string;
  orderNumber: string;
  customerName: string;
  items: OrderItem[];
  status: 'NEW' | 'IN_PROGRESS' | 'READY';
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
}

@Component({
  selector: 'bake-app-queue',
  standalone: true,
  imports: [
    CommonModule,
    MatIconModule,
    MatButtonModule,
    MatCheckboxModule,
  ],
  template: `
    <div class="queue-container">
      <!-- NEW Column -->
      <div class="queue-column">
        <div class="column-header column-header--new">
          <div class="column-header-left">
            <mat-icon>fiber_new</mat-icon>
            <span class="column-title">NEW</span>
          </div>
          <span class="column-count">{{ newOrders.length }}</span>
        </div>
        <div class="column-body">
          <div
            *ngFor="let order of newOrders"
            class="order-card order-card--new"
            (click)="navigateToDetail(order.id)"
          >
            <div class="card-top">
              <span class="order-number">#{{ order.orderNumber }}</span>
              <span class="elapsed-time">
                <mat-icon class="time-icon">schedule</mat-icon>
                {{ getElapsedTime(order.createdAt) }}
              </span>
            </div>

            <div class="customer-name">{{ order.customerName }}</div>

            <ul class="item-list">
              <li *ngFor="let item of order.items" class="item-row">
                <span class="item-qty">{{ item.quantity }}x</span>
                <span class="item-name">{{ item.name }}</span>
              </li>
            </ul>

            <button
              class="action-btn action-btn--start"
              (click)="startOrder(order); $event.stopPropagation()"
            >
              <mat-icon>play_arrow</mat-icon>
              START
            </button>
          </div>
        </div>
      </div>

      <!-- IN PROGRESS Column -->
      <div class="queue-column">
        <div class="column-header column-header--progress">
          <div class="column-header-left">
            <mat-icon>autorenew</mat-icon>
            <span class="column-title">IN PROGRESS</span>
          </div>
          <span class="column-count">{{ inProgressOrders.length }}</span>
        </div>
        <div class="column-body">
          <div
            *ngFor="let order of inProgressOrders"
            class="order-card order-card--progress"
            (click)="navigateToDetail(order.id)"
          >
            <div class="card-top">
              <span class="order-number">#{{ order.orderNumber }}</span>
              <span class="elapsed-time elapsed-time--active">
                <mat-icon class="time-icon">timer</mat-icon>
                {{ getElapsedTime(order.startedAt!) }}
              </span>
            </div>

            <div class="customer-name">{{ order.customerName }}</div>

            <ul class="item-list item-list--checkable">
              <li *ngFor="let item of order.items" class="item-row item-row--checkable">
                <mat-checkbox
                  [checked]="item.done"
                  (change)="toggleItem(item); $event.source?.focus()"
                  (click)="$event.stopPropagation()"
                  color="accent"
                  class="item-checkbox"
                >
                  <span [class.item-done]="item.done">
                    <span class="item-qty">{{ item.quantity }}x</span>
                    {{ item.name }}
                  </span>
                </mat-checkbox>
              </li>
            </ul>

            <div class="progress-bar-container">
              <div
                class="progress-bar"
                [style.width.%]="getProgress(order)"
              ></div>
            </div>

            <button
              class="action-btn action-btn--done"
              (click)="completeOrder(order); $event.stopPropagation()"
            >
              <mat-icon>check_circle</mat-icon>
              DONE
            </button>
          </div>
        </div>
      </div>

      <!-- READY Column -->
      <div class="queue-column">
        <div class="column-header column-header--ready">
          <div class="column-header-left">
            <mat-icon>check_circle</mat-icon>
            <span class="column-title">READY</span>
          </div>
          <span class="column-count">{{ readyOrders.length }}</span>
        </div>
        <div class="column-body">
          <div
            *ngFor="let order of readyOrders"
            class="order-card order-card--ready"
          >
            <div class="card-top">
              <span class="order-number">#{{ order.orderNumber }}</span>
              <span class="elapsed-time elapsed-time--ready">
                <mat-icon class="time-icon">done_all</mat-icon>
                {{ getElapsedTime(order.completedAt!) }}
              </span>
            </div>

            <div class="customer-name customer-name--ready">
              {{ order.customerName }}
            </div>

            <ul class="item-list">
              <li *ngFor="let item of order.items" class="item-row">
                <span class="item-qty">{{ item.quantity }}x</span>
                <span class="item-name">{{ item.name }}</span>
              </li>
            </ul>

            <button
              class="action-btn action-btn--pickup"
              (click)="pickupOrder(order)"
            >
              <mat-icon>delivery_dining</mat-icon>
              PICKED UP
            </button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
      height: 100%;
    }

    .queue-container {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr;
      gap: 16px;
      padding: 16px;
      height: 100%;
      overflow: hidden;
    }

    .queue-column {
      display: flex;
      flex-direction: column;
      background-color: rgba(255, 255, 255, 0.03);
      border-radius: 12px;
      overflow: hidden;
    }

    .column-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 16px 20px;
      font-size: 16px;
      font-weight: 700;
      letter-spacing: 1px;
      text-transform: uppercase;
    }

    .column-header-left {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .column-header mat-icon {
      font-size: 22px;
      width: 22px;
      height: 22px;
    }

    .column-header--new {
      background-color: rgba(79, 195, 247, 0.15);
      color: #4FC3F7;
      border-bottom: 3px solid #4FC3F7;
    }

    .column-header--progress {
      background-color: rgba(255, 183, 77, 0.15);
      color: #FFB74D;
      border-bottom: 3px solid #FFB74D;
    }

    .column-header--ready {
      background-color: rgba(129, 199, 132, 0.15);
      color: #81C784;
      border-bottom: 3px solid #81C784;
    }

    .column-count {
      background-color: rgba(255, 255, 255, 0.15);
      padding: 4px 12px;
      border-radius: 16px;
      font-family: 'JetBrains Mono', monospace;
      font-size: 16px;
      font-weight: 700;
    }

    .column-body {
      flex: 1;
      overflow-y: auto;
      padding: 12px;
      display: flex;
      flex-direction: column;
      gap: 12px;
    }

    /* Order Cards */
    .order-card {
      background-color: #16213E;
      border-radius: 12px;
      padding: 20px;
      border-left: 5px solid transparent;
      cursor: pointer;
      transition: transform 0.15s ease, box-shadow 0.15s ease;
    }

    .order-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
    }

    .order-card--new {
      border-left-color: #4FC3F7;
    }

    .order-card--progress {
      border-left-color: #FFB74D;
    }

    .order-card--ready {
      border-left-color: #81C784;
    }

    .card-top {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 8px;
    }

    .order-number {
      font-family: 'JetBrains Mono', monospace;
      font-size: 22px;
      font-weight: 700;
      color: #FFFFFF;
    }

    .elapsed-time {
      display: flex;
      align-items: center;
      gap: 4px;
      font-family: 'JetBrains Mono', monospace;
      font-size: 16px;
      font-weight: 500;
      color: rgba(255, 255, 255, 0.5);
    }

    .elapsed-time--active {
      color: #FFB74D;
    }

    .elapsed-time--ready {
      color: #81C784;
    }

    .time-icon {
      font-size: 16px;
      width: 16px;
      height: 16px;
    }

    .customer-name {
      font-size: 15px;
      font-weight: 500;
      color: rgba(255, 255, 255, 0.65);
      margin-bottom: 14px;
    }

    .customer-name--ready {
      font-size: 20px;
      font-weight: 700;
      color: #81C784;
      text-align: center;
      margin: 8px 0 16px;
    }

    .item-list {
      list-style: none;
      padding: 0;
      margin: 0 0 16px 0;
    }

    .item-row {
      display: flex;
      align-items: center;
      padding: 6px 0;
      font-size: 16px;
      color: rgba(255, 255, 255, 0.85);
      border-bottom: 1px solid rgba(255, 255, 255, 0.06);
    }

    .item-row:last-child {
      border-bottom: none;
    }

    .item-row--checkable {
      padding: 2px 0;
    }

    .item-qty {
      font-weight: 700;
      margin-right: 10px;
      color: #FFB74D;
      min-width: 32px;
      font-family: 'JetBrains Mono', monospace;
    }

    .item-name {
      flex: 1;
    }

    .item-done {
      text-decoration: line-through;
      color: rgba(255, 255, 255, 0.35);
    }

    .item-checkbox {
      width: 100%;
    }

    .item-checkbox ::ng-deep .mdc-form-field {
      color: rgba(255, 255, 255, 0.85);
      font-size: 16px;
    }

    .item-checkbox ::ng-deep .mdc-checkbox__background {
      border-color: rgba(255, 255, 255, 0.4) !important;
    }

    /* Progress bar */
    .progress-bar-container {
      width: 100%;
      height: 6px;
      background-color: rgba(255, 255, 255, 0.1);
      border-radius: 3px;
      margin-bottom: 16px;
      overflow: hidden;
    }

    .progress-bar {
      height: 100%;
      background: linear-gradient(90deg, #FFB74D, #FF9800);
      border-radius: 3px;
      transition: width 0.3s ease;
    }

    /* Action Buttons - 80px minimum touch targets */
    .action-btn {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 10px;
      width: 100%;
      min-height: 80px;
      border: none;
      border-radius: 10px;
      font-family: 'Inter', sans-serif;
      font-size: 18px;
      font-weight: 700;
      letter-spacing: 1px;
      cursor: pointer;
      transition: all 0.15s ease;
      text-transform: uppercase;
    }

    .action-btn mat-icon {
      font-size: 26px;
      width: 26px;
      height: 26px;
    }

    .action-btn--start {
      background-color: #4FC3F7;
      color: #0D1B2A;
    }

    .action-btn--start:hover {
      background-color: #29B6F6;
      box-shadow: 0 4px 16px rgba(79, 195, 247, 0.35);
    }

    .action-btn--start:active {
      transform: scale(0.98);
    }

    .action-btn--done {
      background-color: #FFB74D;
      color: #1A1A2E;
    }

    .action-btn--done:hover {
      background-color: #FFA726;
      box-shadow: 0 4px 16px rgba(255, 183, 77, 0.35);
    }

    .action-btn--done:active {
      transform: scale(0.98);
    }

    .action-btn--pickup {
      background-color: #81C784;
      color: #1A1A2E;
    }

    .action-btn--pickup:hover {
      background-color: #66BB6A;
      box-shadow: 0 4px 16px rgba(129, 199, 132, 0.35);
    }

    .action-btn--pickup:active {
      transform: scale(0.98);
    }
  `],
})
export class QueueComponent implements OnInit, OnDestroy {
  orders: KitchenOrder[] = [];
  private timerInterval: ReturnType<typeof setInterval> | null = null;
  private socket: Socket | null = null;

  constructor(
    private router: Router,
    private apiClient: ApiClientService,
    private authService: AuthService,
  ) {}

  get newOrders(): KitchenOrder[] {
    return this.orders.filter(o => o.status === 'NEW');
  }

  get inProgressOrders(): KitchenOrder[] {
    return this.orders.filter(o => o.status === 'IN_PROGRESS');
  }

  get readyOrders(): KitchenOrder[] {
    return this.orders.filter(o => o.status === 'READY');
  }

  ngOnInit(): void {
    this.loadOrders();
    this.connectWebSocket();
    this.timerInterval = setInterval(() => {
      this.orders = [...this.orders];
    }, 1000);
  }

  ngOnDestroy(): void {
    if (this.timerInterval) {
      clearInterval(this.timerInterval);
    }
    if (this.socket) {
      this.socket.disconnect();
      this.socket = null;
    }
  }

  startOrder(order: KitchenOrder): void {
    this.apiClient
      .put(`/v1/orders/${order.id}/status`, { status: 'in_progress' })
      .subscribe({
        next: () => {
          order.status = 'IN_PROGRESS';
          order.startedAt = new Date();
        },
      });
  }

  completeOrder(order: KitchenOrder): void {
    this.apiClient
      .put(`/v1/orders/${order.id}/status`, { status: 'completed' })
      .subscribe({
        next: () => {
          order.status = 'READY';
          order.completedAt = new Date();
          order.items.forEach(item => item.done = true);
        },
      });
  }

  pickupOrder(order: KitchenOrder): void {
    this.apiClient
      .put(`/v1/orders/${order.id}/status`, { status: 'delivered' })
      .subscribe({
        next: () => {
          this.orders = this.orders.filter(o => o.id !== order.id);
        },
      });
  }

  toggleItem(item: OrderItem): void {
    item.done = !item.done;
  }

  getProgress(order: KitchenOrder): number {
    if (order.items.length === 0) return 0;
    const doneCount = order.items.filter(i => i.done).length;
    return Math.round((doneCount / order.items.length) * 100);
  }

  getElapsedTime(since: Date): string {
    const now = new Date();
    const diffMs = now.getTime() - since.getTime();
    const totalSeconds = Math.floor(diffMs / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;

    if (minutes >= 60) {
      const hours = Math.floor(minutes / 60);
      const mins = minutes % 60;
      return `${hours}h ${mins.toString().padStart(2, '0')}m`;
    }

    return `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  }

  navigateToDetail(orderId: string): void {
    this.router.navigate(['/orders', orderId]);
  }

  private connectWebSocket(): void {
    const token = this.authService.getToken();
    this.socket = io('http://localhost:3000', {
      auth: { token },
    });

    this.socket.on('order:new', () => {
      this.loadOrders();
    });

    this.socket.on('order:statusChanged', (payload: { orderId: string; newStatus: string }) => {
      const statusMap: Record<string, KitchenOrder['status']> = {
        pending: 'NEW',
        confirmed: 'NEW',
        in_progress: 'IN_PROGRESS',
        completed: 'READY',
      };
      const mappedStatus = statusMap[payload.newStatus];
      if (mappedStatus) {
        const order = this.orders.find(o => o.id === payload.orderId);
        if (order) {
          order.status = mappedStatus;
          if (mappedStatus === 'IN_PROGRESS') {
            order.startedAt = new Date();
          } else if (mappedStatus === 'READY') {
            order.completedAt = new Date();
            order.items.forEach(item => item.done = true);
          }
          this.orders = [...this.orders];
        }
      } else if (['delivered', 'cancelled'].includes(payload.newStatus)) {
        this.orders = this.orders.filter(o => o.id !== payload.orderId);
      }
    });
  }

  private loadOrders(): void {
    this.apiClient
      .get<PaginatedResponse<Order>>('/v1/orders?limit=50')
      .subscribe({
        next: (response) => {
          this.orders = response.data
            .filter((o) => ['pending', 'confirmed', 'in_progress', 'completed'].includes(o.status))
            .map((o) => this.mapOrder(o));
        },
      });
  }

  private mapOrder(o: Order): KitchenOrder {
    const statusMap: Record<string, KitchenOrder['status']> = {
      pending: 'NEW',
      confirmed: 'NEW',
      in_progress: 'IN_PROGRESS',
      completed: 'READY',
    };
    return {
      id: o.id,
      orderNumber: o.orderNumber,
      customerName: o.notes || `Order ${o.orderNumber}`,
      status: statusMap[o.status] || 'NEW',
      createdAt: new Date(o.createdAt),
      startedAt: o.status === 'in_progress' ? new Date(o.updatedAt) : undefined,
      completedAt: o.status === 'completed' ? new Date(o.updatedAt) : undefined,
      items: o.items.map((item) => ({
        name: item.product?.name || 'Item',
        quantity: item.quantity,
        done: o.status === 'completed',
      })),
    };
  }
}

// apps/kitchen-screen/src/pages/queue.tsx
import { useEffect, useMemo, useState, useCallback } from 'react';
import { useNavigate } from 'react-router';
import { useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { useOrders, useUpdateOrderStatus } from '@bake-app/react/api-client';
import { useWebSocketStore } from '@bake-app/react/store';
import { useAuth } from '@bake-app/react/auth';
import type { Order, OrderItem } from '@bake-app/shared-types';
import {
  ChefHat,
  Clock,
  Play,
  CheckCircle2,
  HandMetal,
  LogOut,
  Factory,
} from 'lucide-react';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface KitchenOrderItem extends OrderItem {
  done: boolean;
}

interface KitchenOrder {
  id: string;
  orderNumber: string;
  status: 'new' | 'in_progress' | 'ready';
  customer: string;
  items: KitchenOrderItem[];
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
}

type Column = 'new' | 'in_progress' | 'ready';

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function mapStatus(apiStatus: string): Column | null {
  switch (apiStatus) {
    case 'pending':
    case 'confirmed':
      return 'new';
    case 'in_progress':
      return 'in_progress';
    case 'completed':
      return 'ready';
    default:
      return null; // delivered, cancelled
  }
}

function elapsed(from: Date | string): string {
  const diff = Math.max(
    0,
    Math.floor((Date.now() - new Date(from).getTime()) / 1000),
  );
  const m = Math.floor(diff / 60);
  const s = diff % 60;
  if (m >= 60) {
    const h = Math.floor(m / 60);
    return `${h}h ${m % 60}m`;
  }
  return `${m}:${s.toString().padStart(2, '0')}`;
}

function toKitchenOrder(order: Order): KitchenOrder | null {
  const col = mapStatus(order.status);
  if (!col) return null;
  return {
    id: order.id,
    orderNumber: order.orderNumber,
    status: col,
    customer: order.notes || '',
    items: (order.items || []).map((item) => ({ ...item, done: false })),
    createdAt: new Date(order.createdAt),
    startedAt: order.status === 'in_progress' ? new Date(order.updatedAt) : undefined,
    completedAt: order.status === 'completed' ? new Date(order.updatedAt) : undefined,
  };
}

/* ------------------------------------------------------------------ */
/*  Column config                                                      */
/* ------------------------------------------------------------------ */

const COLUMNS: {
  key: Column;
  label: string;
  color: string;
  bgClass: string;
  borderClass: string;
  textClass: string;
}[] = [
  {
    key: 'new',
    label: 'NEW',
    color: '#4FC3F7',
    bgClass: 'bg-[#4FC3F7]/10',
    borderClass: 'border-l-[#4FC3F7]',
    textClass: 'text-[#4FC3F7]',
  },
  {
    key: 'in_progress',
    label: 'IN PROGRESS',
    color: '#FFB74D',
    bgClass: 'bg-[#FFB74D]/10',
    borderClass: 'border-l-[#FFB74D]',
    textClass: 'text-[#FFB74D]',
  },
  {
    key: 'ready',
    label: 'READY',
    color: '#81C784',
    bgClass: 'bg-[#81C784]/10',
    borderClass: 'border-l-[#81C784]',
    textClass: 'text-[#81C784]',
  },
];

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function QueuePage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { token, logout } = useAuth();
  const { connect, disconnect } = useWebSocketStore();
  const { data, isLoading } = useOrders({ limit: 50 });
  const updateStatus = useUpdateOrderStatus();

  // Force re-render every second for elapsed timers
  const [, setTick] = useState(0);
  useEffect(() => {
    const id = setInterval(() => setTick((t) => t + 1), 1000);
    return () => clearInterval(id);
  }, []);

  // WebSocket connection
  useEffect(() => {
    if (token) {
      connect(token, queryClient);
    }
    return () => disconnect();
  }, [token, connect, disconnect, queryClient]);

  // Track checked items locally per order
  const [checkedItems, setCheckedItems] = useState<Record<string, Set<string>>>(
    {},
  );

  const toggleItem = useCallback((orderId: string, itemId: string) => {
    setCheckedItems((prev) => {
      const set = new Set(prev[orderId] || []);
      if (set.has(itemId)) {
        set.delete(itemId);
      } else {
        set.add(itemId);
      }
      return { ...prev, [orderId]: set };
    });
  }, []);

  // Map API orders to kitchen orders
  const orders = useMemo(() => {
    const items = data?.data ?? (Array.isArray(data) ? data : []);
    return (items as Order[])
      .map(toKitchenOrder)
      .filter((o): o is KitchenOrder => o !== null);
  }, [data]);

  const columns = useMemo(() => {
    const grouped: Record<Column, KitchenOrder[]> = {
      new: [],
      in_progress: [],
      ready: [],
    };
    for (const order of orders) {
      grouped[order.status].push(order);
    }
    return grouped;
  }, [orders]);

  // Actions
  function handleStart(orderId: string) {
    updateStatus.mutate(
      { id: orderId, status: 'in_progress' },
      {
        onSuccess: () => toast.success('Order started'),
        onError: () => toast.error('Failed to start order'),
      },
    );
  }

  function handleDone(orderId: string) {
    updateStatus.mutate(
      { id: orderId, status: 'completed' },
      {
        onSuccess: () => {
          toast.success('Order completed');
          setCheckedItems((prev) => {
            const next = { ...prev };
            delete next[orderId];
            return next;
          });
        },
        onError: () => toast.error('Failed to complete order'),
      },
    );
  }

  function handlePickedUp(orderId: string) {
    updateStatus.mutate(
      { id: orderId, status: 'delivered' },
      {
        onSuccess: () => toast.success('Order picked up'),
        onError: () => toast.error('Failed to mark as picked up'),
      },
    );
  }

  function handleLogout() {
    disconnect();
    logout();
    navigate('/login');
  }

  if (isLoading) {
    return (
      <div className="flex h-screen items-center justify-center bg-[#0D1B2A]">
        <div className="flex flex-col items-center gap-3">
          <ChefHat className="h-12 w-12 animate-pulse text-orange-400" />
          <p className="text-gray-400">Loading orders...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-screen flex-col bg-[#0D1B2A]">
      {/* Header */}
      <header className="flex items-center justify-between border-b border-white/5 px-6 py-3">
        <div className="flex items-center gap-3">
          <ChefHat className="h-7 w-7 text-orange-400" />
          <h1 className="text-xl font-bold text-white">Kitchen Display</h1>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/production')}
            className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm text-gray-300 transition-colors hover:bg-white/5"
          >
            <Factory className="h-4 w-4" />
            Production
          </button>
          <button
            onClick={handleLogout}
            className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm text-gray-300 transition-colors hover:bg-white/5"
          >
            <LogOut className="h-4 w-4" />
            Logout
          </button>
        </div>
      </header>

      {/* Kanban columns */}
      <div className="grid flex-1 grid-cols-3 gap-4 overflow-hidden p-4">
        {COLUMNS.map((col) => (
          <div key={col.key} className="flex flex-col overflow-hidden rounded-xl border border-white/5">
            {/* Column header */}
            <div
              className={`flex items-center justify-between px-4 py-3 ${col.bgClass}`}
            >
              <span className={`text-sm font-bold tracking-wider ${col.textClass}`}>
                {col.label}
              </span>
              <span
                className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${col.textClass}`}
                style={{ backgroundColor: col.color + '30' }}
              >
                {columns[col.key].length}
              </span>
            </div>

            {/* Cards */}
            <div className="flex-1 overflow-y-auto p-3 space-y-3">
              {columns[col.key].map((order) => (
                <OrderCard
                  key={order.id}
                  order={order}
                  column={col}
                  checkedItems={checkedItems[order.id] || new Set()}
                  onToggleItem={toggleItem}
                  onStart={handleStart}
                  onDone={handleDone}
                  onPickedUp={handlePickedUp}
                  onCardClick={() => navigate(`/orders/${order.id}`)}
                />
              ))}
              {columns[col.key].length === 0 && (
                <div className="flex h-32 items-center justify-center text-sm text-gray-600">
                  No orders
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Order Card                                                         */
/* ------------------------------------------------------------------ */

interface OrderCardProps {
  order: KitchenOrder;
  column: (typeof COLUMNS)[number];
  checkedItems: Set<string>;
  onToggleItem: (orderId: string, itemId: string) => void;
  onStart: (id: string) => void;
  onDone: (id: string) => void;
  onPickedUp: (id: string) => void;
  onCardClick: () => void;
}

function OrderCard({
  order,
  column,
  checkedItems,
  onToggleItem,
  onStart,
  onDone,
  onPickedUp,
  onCardClick,
}: OrderCardProps) {
  const doneCount = checkedItems.size;
  const totalItems = order.items.length;
  const progress = totalItems > 0 ? (doneCount / totalItems) * 100 : 0;

  const timerRef =
    order.status === 'in_progress'
      ? order.startedAt
      : order.status === 'ready'
        ? order.completedAt
        : order.createdAt;

  return (
    <div
      className={`rounded-xl bg-[#16213E] border-l-4 ${column.borderClass} transition-all duration-200 hover:shadow-lg hover:shadow-black/30`}
      style={{ transform: 'translateY(0)' }}
      onMouseEnter={(e) => (e.currentTarget.style.transform = 'translateY(-2px)')}
      onMouseLeave={(e) => (e.currentTarget.style.transform = 'translateY(0)')}
    >
      {/* Card header */}
      <div
        className="flex items-center justify-between px-4 pt-4 pb-2 cursor-pointer"
        onClick={onCardClick}
      >
        <span className="font-mono text-xl font-bold text-white">
          #{order.orderNumber}
        </span>
        <div className={`flex items-center gap-1 text-sm ${column.textClass}`}>
          <Clock className="h-3.5 w-3.5" />
          <span className="font-mono">{elapsed(timerRef!)}</span>
        </div>
      </div>

      {/* Customer */}
      {order.customer && (
        <div className="px-4 pb-2">
          <span
            className={`text-sm font-medium ${
              order.status === 'ready'
                ? 'text-lg font-bold text-[#81C784]'
                : 'text-gray-400'
            }`}
          >
            {order.customer}
          </span>
        </div>
      )}

      {/* Items */}
      <div className="px-4 pb-3">
        <ul className="space-y-1.5">
          {order.items.map((item) => {
            const isChecked = checkedItems.has(item.id);
            const productName = item.product?.name ?? `Product`;
            return (
              <li
                key={item.id}
                className="flex items-center gap-2 text-sm"
              >
                {order.status === 'in_progress' && (
                  <input
                    type="checkbox"
                    checked={isChecked}
                    onChange={() => onToggleItem(order.id, item.id)}
                    className="h-4 w-4 shrink-0 cursor-pointer rounded border-white/20 bg-transparent accent-[#FFB74D]"
                  />
                )}
                <span
                  className={`${
                    isChecked ? 'text-gray-500 line-through' : 'text-gray-300'
                  }`}
                >
                  <span className="font-mono font-semibold text-[#FFB74D]">
                    {item.quantity}x
                  </span>{' '}
                  {productName}
                </span>
              </li>
            );
          })}
        </ul>
      </div>

      {/* Progress bar (in_progress only) */}
      {order.status === 'in_progress' && totalItems > 0 && (
        <div className="px-4 pb-3">
          <div className="h-1.5 overflow-hidden rounded-full bg-white/5">
            <div
              className="h-full rounded-full transition-all duration-300"
              style={{
                width: `${progress}%`,
                background: 'linear-gradient(90deg, #FFB74D, #FF9800)',
              }}
            />
          </div>
          <p className="mt-1 text-right text-xs text-gray-500">
            {doneCount}/{totalItems} items
          </p>
        </div>
      )}

      {/* Action button */}
      <div className="px-4 pb-4">
        {order.status === 'new' && (
          <button
            onClick={() => onStart(order.id)}
            className="flex min-h-[80px] w-full items-center justify-center gap-2 rounded-xl bg-[#4FC3F7]/20 text-lg font-bold text-[#4FC3F7] transition-colors hover:bg-[#4FC3F7]/30 active:bg-[#4FC3F7]/40"
          >
            <Play className="h-6 w-6" />
            START
          </button>
        )}
        {order.status === 'in_progress' && (
          <button
            onClick={() => onDone(order.id)}
            className="flex min-h-[80px] w-full items-center justify-center gap-2 rounded-xl bg-[#FFB74D]/20 text-lg font-bold text-[#FFB74D] transition-colors hover:bg-[#FFB74D]/30 active:bg-[#FFB74D]/40"
          >
            <CheckCircle2 className="h-6 w-6" />
            DONE
          </button>
        )}
        {order.status === 'ready' && (
          <button
            onClick={() => onPickedUp(order.id)}
            className="flex min-h-[80px] w-full items-center justify-center gap-2 rounded-xl bg-[#81C784]/20 text-lg font-bold text-[#81C784] transition-colors hover:bg-[#81C784]/30 active:bg-[#81C784]/40"
          >
            <HandMetal className="h-6 w-6" />
            PICKED UP
          </button>
        )}
      </div>
    </div>
  );
}
