// apps/pos-app/src/pages/orders.tsx
import { useMemo } from 'react';
import { useNavigate } from 'react-router';
import {
  ArrowLeft,
  ClipboardList,
  CheckCircle2,
  Clock,
  XCircle,
} from 'lucide-react';
import { useOrders } from '@bake-app/react/api-client';
import { DataTable, LoadingSpinner, type TableColumn } from '@bake-app/react/ui';

export function OrdersPage() {
  const navigate = useNavigate();
  const { data: ordersResponse, isLoading } = useOrders({ limit: 50 });

  const orders = ordersResponse ?? [];

  const stats = useMemo(() => {
    const total = orders.length;
    const completed = orders.filter((o) => o.status === 'completed' || o.status === 'confirmed').length;
    const pending = orders.filter((o) => o.status === 'pending').length;
    const cancelled = orders.filter((o) => o.status === 'cancelled').length;
    return { total, completed, pending, cancelled };
  }, [orders]);

  const columns: TableColumn[] = [
    {
      key: 'orderNumber',
      label: 'Order #',
      render: (value: string) => (
        <span className="font-mono font-semibold text-[#8b4513]">#{value}</span>
      ),
    },
    {
      key: 'createdAt',
      label: 'Date',
      type: 'date',
      sortable: true,
    },
    {
      key: 'items',
      label: 'Items',
      render: (value: any[]) => (
        <span className="text-sm text-gray-700">{value?.length ?? 0} items</span>
      ),
    },
    {
      key: 'total',
      label: 'Total',
      type: 'currency',
      sortable: true,
    },
    {
      key: 'status',
      label: 'Status',
      type: 'badge',
    },
  ];

  return (
    <div className="min-h-screen bg-[#faf3e8]">
      {/* Header */}
      <div className="bg-white border-b border-[#8b4513]/10 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center gap-4">
          <button
            type="button"
            onClick={() => navigate('/pos')}
            className="flex items-center justify-center h-9 w-9 rounded-lg
              bg-[#faf3e8] text-[#5d4037] border border-[#8b4513]/10
              hover:bg-[#f5e6d0] transition-colors cursor-pointer"
          >
            <ArrowLeft size={18} />
          </button>
          <div className="flex items-center gap-2">
            <ClipboardList className="text-[#8b4513]" size={24} />
            <h1 className="text-xl font-bold text-[#3e2723]">Order History</h1>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-6 space-y-6">
        {/* Stats bar */}
        <div className="flex flex-wrap gap-3">
          <div className="flex items-center gap-2 px-4 py-2 bg-white rounded-xl border border-[#8b4513]/10 shadow-sm">
            <ClipboardList size={16} className="text-[#8b4513]" />
            <span className="text-sm font-medium text-[#5d4037]">Total</span>
            <span className="font-bold text-[#3e2723] font-mono">{stats.total}</span>
          </div>
          <div className="flex items-center gap-2 px-4 py-2 bg-green-50 rounded-xl border border-green-200 shadow-sm">
            <CheckCircle2 size={16} className="text-green-600" />
            <span className="text-sm font-medium text-green-700">Completed</span>
            <span className="font-bold text-green-800 font-mono">{stats.completed}</span>
          </div>
          <div className="flex items-center gap-2 px-4 py-2 bg-amber-50 rounded-xl border border-amber-200 shadow-sm">
            <Clock size={16} className="text-amber-600" />
            <span className="text-sm font-medium text-amber-700">Pending</span>
            <span className="font-bold text-amber-800 font-mono">{stats.pending}</span>
          </div>
          {stats.cancelled > 0 && (
            <div className="flex items-center gap-2 px-4 py-2 bg-red-50 rounded-xl border border-red-200 shadow-sm">
              <XCircle size={16} className="text-red-600" />
              <span className="text-sm font-medium text-red-700">Cancelled</span>
              <span className="font-bold text-red-800 font-mono">{stats.cancelled}</span>
            </div>
          )}
        </div>

        {/* Orders table */}
        {isLoading ? (
          <LoadingSpinner message="Loading orders..." />
        ) : (
          <DataTable
            columns={columns}
            data={orders}
            onRowClick={(row) => navigate(`/orders/${row.id}`)}
            searchable
            searchPlaceholder="Search orders..."
            pageSize={10}
          />
        )}
      </div>
    </div>
  );
}

// apps/pos-app/src/app/pages/orders/orders.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import {
  BakeDataTableComponent,
  BakeStatusBadgeComponent,
  TableColumn,
} from '@bake-app/ui-components';
import { ApiClientService } from '@bake-app/api-client';
import { Order } from '@bake-app/shared-types';

interface OrderRow {
  id: string;
  orderNumber: string;
  date: Date;
  items: string;
  total: number;
  status: string;
}

interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

@Component({
  selector: 'bake-app-orders',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    BakeDataTableComponent,
    BakeStatusBadgeComponent,
  ],
  template: `
    <div class="orders-page">
      <div class="page-header">
        <div class="header-left">
          <h1>Order History</h1>
          <p class="subtitle">View and manage all orders</p>
        </div>
        <div class="header-stats">
          <div class="stat-pill">
            <mat-icon>receipt</mat-icon>
            <span>{{ orders.length }} orders today</span>
          </div>
          <div class="stat-pill completed">
            <mat-icon>check_circle</mat-icon>
            <span>{{ completedCount }} completed</span>
          </div>
          <div class="stat-pill pending">
            <mat-icon>schedule</mat-icon>
            <span>{{ pendingCount }} pending</span>
          </div>
        </div>
      </div>

      <bake-data-table
        [columns]="columns"
        [data]="orders"
        [loading]="loading"
        [searchable]="true"
        (rowClick)="onRowClick($event)"
        (rowAction)="onRowAction($event)"
      ></bake-data-table>
    </div>
  `,
  styles: [
    `
      .orders-page {
        padding: 24px;
        background-color: #faf3e8;
        min-height: calc(100vh - 64px);
      }

      .page-header {
        display: flex;
        align-items: flex-start;
        justify-content: space-between;
        margin-bottom: 24px;
      }

      .header-left h1 {
        font-size: 24px;
        font-weight: 700;
        color: #3e2723;
        margin: 0 0 4px 0;
      }

      .subtitle {
        font-size: 14px;
        color: #8d6e63;
        margin: 0;
      }

      .header-stats {
        display: flex;
        gap: 12px;
      }

      .stat-pill {
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 8px 14px;
        background-color: #fff;
        border-radius: 20px;
        font-size: 13px;
        font-weight: 500;
        color: #5d4037;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
      }

      .stat-pill mat-icon {
        font-size: 18px;
        width: 18px;
        height: 18px;
      }

      .stat-pill.completed {
        color: #2e7d32;
        background-color: #e8f5e9;
      }

      .stat-pill.pending {
        color: #f57f17;
        background-color: #fff8e1;
      }
    `,
  ],
})
export class OrdersComponent implements OnInit {
  orders: OrderRow[] = [];
  loading = true;
  errorMessage = '';

  columns: TableColumn[] = [
    { key: 'orderNumber', label: 'Order #', sortable: true, width: '100px' },
    { key: 'date', label: 'Date', type: 'date', sortable: true, width: '160px' },
    { key: 'items', label: 'Items', sortable: false },
    { key: 'total', label: 'Total', type: 'currency', sortable: true, width: '120px' },
    { key: 'status', label: 'Status', type: 'badge', sortable: true, width: '130px' },
    { key: 'actions', label: '', type: 'actions', width: '100px' },
  ];

  constructor(
    private router: Router,
    private apiClient: ApiClientService,
  ) {}

  ngOnInit(): void {
    this.loadOrders();
  }

  loadOrders(): void {
    this.loading = true;
    this.errorMessage = '';
    this.apiClient.get<PaginatedResponse<Order>>('/v1/orders?limit=50').subscribe({
      next: (response) => {
        this.orders = response.data.map((order) => ({
          id: order.id,
          orderNumber: order.orderNumber,
          date: new Date(order.createdAt),
          items: order.items
            .map((item) => `${item.product?.name || 'Item'} x${item.quantity}`)
            .join(', '),
          total: order.total,
          status: this.formatStatus(order.status),
        }));
        this.loading = false;
      },
      error: () => {
        this.errorMessage = 'Failed to load orders.';
        this.loading = false;
      },
    });
  }

  private formatStatus(status: string): string {
    const statusMap: Record<string, string> = {
      pending: 'Pending',
      confirmed: 'Confirmed',
      in_progress: 'In Progress',
      completed: 'Completed',
      cancelled: 'Cancelled',
    };
    return statusMap[status] || status;
  }

  get completedCount(): number {
    return this.orders.filter((o) => o.status === 'Completed').length;
  }

  get pendingCount(): number {
    return this.orders.filter(
      (o) => o.status === 'Pending' || o.status === 'In Progress'
    ).length;
  }

  onRowClick(row: OrderRow): void {
    this.router.navigate(['/orders', row.id]);
  }

  onRowAction(event: { action: string; row: OrderRow }): void {
    if (event.action === 'edit') {
      this.router.navigate(['/orders', event.row.id]);
    }
  }
}
