// apps/admin-dashboard/src/app/pages/inventory/inventory.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import {
  BakeConfirmationService,
  BakeDataTableComponent,
  BakePageContainerComponent,
  BakeToastService,
  TableAction,
  TableColumn,
} from '@bake-app/ui-components';
import { ApiClientService } from '@bake-app/api-client';
import { Ingredient, InventoryItem } from '@bake-app/shared-types';
import {
  AddInventoryDialogComponent,
  AddInventoryDialogResult,
} from './add-inventory-dialog.component';

interface InventoryRow {
  id: string;
  title: string;
  ingredient: string;
  category: string;
  packages: string;
  quantity: string;
  unit: string;
  minLevel: number;
  status: string;
}

@Component({
  selector: 'bake-app-inventory',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatDialogModule,
    BakeDataTableComponent,
    BakePageContainerComponent,
  ],
  template: `
    <bake-page-container title="Inventory" subtitle="Stock levels and ingredient management">
      <div class="page-actions">
        <button mat-flat-button class="add-btn" (click)="openAddDialog()">
          <mat-icon>add</mat-icon>
          Add Inventory
        </button>
      </div>

      <!-- Low Stock Alert Banner -->
      <div class="alert-banner" *ngIf="lowStockCount > 0">
        <mat-icon class="alert-banner-icon">warning</mat-icon>
        <div class="alert-banner-content">
          <span class="alert-banner-title">Low Stock Alert</span>
          <span class="alert-banner-message">
            {{ lowStockCount }} ingredient{{ lowStockCount > 1 ? 's' : '' }}
            {{ lowStockCount > 1 ? 'are' : 'is' }} below minimum level.
            {{ outOfStockCount }} item{{ outOfStockCount > 1 ? 's' : '' }} out of stock.
          </span>
        </div>
        <button mat-flat-button class="alert-banner-btn">
          <mat-icon>shopping_cart</mat-icon>
          Create Order
        </button>
      </div>

      <!-- Summary Cards -->
      <div class="summary-grid">
        <mat-card class="summary-card">
          <mat-card-content>
            <div class="summary-item">
              <mat-icon class="summary-icon icon-total">inventory_2</mat-icon>
              <div class="summary-details">
                <span class="summary-value">{{ inventoryData.length }}</span>
                <span class="summary-label">Total Items</span>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
        <mat-card class="summary-card">
          <mat-card-content>
            <div class="summary-item">
              <mat-icon class="summary-icon icon-ok">check_circle</mat-icon>
              <div class="summary-details">
                <span class="summary-value">{{ inStockCount }}</span>
                <span class="summary-label">In Stock</span>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
        <mat-card class="summary-card">
          <mat-card-content>
            <div class="summary-item">
              <mat-icon class="summary-icon icon-low">warning</mat-icon>
              <div class="summary-details">
                <span class="summary-value">{{ lowStockCount }}</span>
                <span class="summary-label">Low Stock</span>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
        <mat-card class="summary-card">
          <mat-card-content>
            <div class="summary-item">
              <mat-icon class="summary-icon icon-out">error</mat-icon>
              <div class="summary-details">
                <span class="summary-value">{{ outOfStockCount }}</span>
                <span class="summary-label">Out of Stock</span>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
      </div>

      <!-- Inventory Table -->
      <mat-card class="table-card">
        <mat-card-content>
          <bake-data-table
            [columns]="columns"
            [data]="inventoryData"
            [loading]="loading"
            [searchable]="true"
            (rowAction)="onRowAction($event)"
            (rowClick)="onRowClick($event)"
          ></bake-data-table>
        </mat-card-content>
      </mat-card>
    </bake-page-container>
  `,
  styles: [
    `
      .alert-banner {
        display: flex;
        align-items: center;
        gap: 16px;
        padding: 16px 20px;
        background-color: #fff8e1;
        border: 1px solid #ffe082;
        border-radius: 12px;
        margin-bottom: 24px;
      }

      .alert-banner-icon {
        font-size: 28px;
        width: 28px;
        height: 28px;
        color: #f57f17;
        flex-shrink: 0;
      }

      .alert-banner-content {
        display: flex;
        flex-direction: column;
        gap: 2px;
        flex: 1;
      }

      .alert-banner-title {
        font-size: 14px;
        font-weight: 600;
        color: #e65100;
      }

      .alert-banner-message {
        font-size: 13px;
        color: #5d4037;
      }

      .alert-banner-btn {
        background-color: #8b4513 !important;
        color: #ffffff !important;
        border-radius: 8px;
        flex-shrink: 0;
      }

      .summary-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 16px;
        margin-bottom: 24px;
      }

      .summary-card {
        border-radius: 12px;
      }

      .summary-item {
        display: flex;
        align-items: center;
        gap: 12px;
      }

      .summary-icon {
        font-size: 32px;
        width: 32px;
        height: 32px;
      }

      .icon-total {
        color: #8b4513;
      }

      .icon-ok {
        color: #2e7d32;
      }

      .icon-low {
        color: #f57f17;
      }

      .icon-out {
        color: #c62828;
      }

      .summary-details {
        display: flex;
        flex-direction: column;
      }

      .summary-value {
        font-family: 'JetBrains Mono', monospace;
        font-size: 24px;
        font-weight: 700;
        color: #263238;
      }

      .summary-label {
        font-size: 12px;
        color: #78909c;
        font-weight: 500;
      }

      .page-actions {
        display: flex;
        justify-content: flex-end;
        margin-bottom: 16px;
      }

      .add-btn {
        background-color: #8b4513 !important;
        color: #ffffff !important;
        border-radius: 8px;
      }

      .table-card {
        border-radius: 12px;
      }

      @media (max-width: 900px) {
        .summary-grid {
          grid-template-columns: repeat(2, 1fr);
        }
      }

      @media (max-width: 600px) {
        .alert-banner {
          flex-direction: column;
          text-align: center;
        }
        .summary-grid {
          grid-template-columns: 1fr;
        }
      }
    `,
  ],
})
export class InventoryComponent implements OnInit {
  columns: TableColumn[] = [
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'ingredient', label: 'Ingredient', type: 'text' },
    { key: 'category', label: 'Category', type: 'badge', sortable: true },
    { key: 'packages', label: 'Packages', type: 'text', width: '160px' },
    { key: 'quantity', label: 'Qty', type: 'text', width: '120px' },
    { key: 'unit', label: 'Unit', type: 'text', width: '80px' },
    { key: 'minLevel', label: 'Min Level', type: 'number', width: '100px' },
    { key: 'status', label: 'Status', type: 'badge', width: '120px' },
    {
      key: 'actions', label: 'Actions', type: 'actions', width: '140px', sortable: false,
      actions: [
        { action: 'details', icon: 'visibility', tooltip: 'Details' },
        { action: 'edit', icon: 'edit', tooltip: 'Edit' },
        { action: 'delete', icon: 'delete', tooltip: 'Delete', color: 'warn' },
      ],
    },
  ];

  inventoryData: InventoryRow[] = [];
  loading = false;

  private ingredients: Ingredient[] = [];
  private rawItems: any[] = [];

  constructor(
    private apiClient: ApiClientService,
    private dialog: MatDialog,
    private toastService: BakeToastService,
    private confirmService: BakeConfirmationService,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.loadInventory();
    this.loadIngredients();
  }

  private loadIngredients(): void {
    this.apiClient
      .get<{ data: Ingredient[] }>('/v1/ingredients?limit=100')
      .subscribe({
        next: (res) => (this.ingredients = res.data),
        error: () => {},
      });
  }

  private loadInventory(): void {
    this.loading = true;
    this.apiClient
      .get<any[]>('/v1/inventory')
      .subscribe({
        next: (items) => {
          this.rawItems = items;
          this.inventoryData = items.map((item) => {
            const qty = Number(item.quantity || 0);
            const minLevel = item.minStockLevel != null
              ? Number(item.minStockLevel)
              : Number(item.ingredient?.minStockLevel || 0);
            let status = 'In Stock';
            if (qty <= 0) {
              status = 'Out of Stock';
            } else if (minLevel > 0 && qty <= minLevel) {
              status = 'Low Stock';
            }

            // Build packages summary
            const pkgSummary = (item.packages || [])
              .map((p: any) => `${p.size}${p.unit}`)
              .join(', ');

            // Build quantity display with metric equivalent
            const ingredientUnit = item.ingredient?.unit || '';
            let qtyDisplay: string;
            if (qty > 999 && ingredientUnit.toLowerCase() === 'g') {
              qtyDisplay = `${(qty / 1000).toFixed(3)} kg`;
            } else if (qty > 999 && ingredientUnit.toLowerCase() === 'ml') {
              qtyDisplay = `${(qty / 1000).toFixed(3)} L`;
            } else {
              qtyDisplay = `${qty} ${ingredientUnit}`;
            }
            if (item.metricQuantity && item.metricUnit) {
              qtyDisplay += ` (${item.metricQuantity} ${item.metricUnit})`;
            }

            return {
              id: item.id,
              title: item.title || '',
              ingredient: item.ingredient?.name || '',
              category: item.ingredient?.ingredientCategory?.name || item.ingredient?.category || '',
              packages: pkgSummary,
              quantity: qtyDisplay,
              unit: ingredientUnit,
              minLevel,
              status,
            };
          });
          this.loading = false;
        },
        error: () => {
          this.loading = false;
        },
      });
  }

  get lowStockCount(): number {
    return this.inventoryData.filter((i) => i.status === 'Low Stock').length;
  }

  get outOfStockCount(): number {
    return this.inventoryData.filter((i) => i.status === 'Out of Stock').length;
  }

  get inStockCount(): number {
    return this.inventoryData.filter((i) => i.status === 'In Stock').length;
  }

  openAddDialog(): void {
    const ref = this.dialog.open(AddInventoryDialogComponent, {
      data: { ingredients: this.ingredients, mode: 'create' },
      width: '500px',
    });
    ref.afterClosed().subscribe((result: AddInventoryDialogResult | undefined) => {
      if (result) {
        this.apiClient.post('/v1/inventory', result).subscribe({
          next: () => {
            this.toastService.success('Inventory added successfully');
            this.loadInventory();
          },
          error: () => this.toastService.error('Failed to add inventory'),
        });
      }
    });
  }

  onRowClick(row: InventoryRow): void {
    this.router.navigate(['/inventory', row.id]);
  }

  onRowAction(event: { action: string; row: InventoryRow }): void {
    if (event.action === 'details') {
      this.router.navigate(['/inventory', event.row.id]);
    } else if (event.action === 'delete') {
      this.confirmService
        .confirm({
          title: 'Delete Inventory Item',
          message: `Are you sure you want to delete "${event.row.title}"? This action cannot be undone.`,
          confirmText: 'Delete',
          confirmColor: 'warn',
        })
        .subscribe((confirmed) => {
          if (confirmed) {
            this.apiClient.delete(`/v1/inventory/${event.row.id}`).subscribe({
              next: () => {
                this.inventoryData = this.inventoryData.filter(
                  (i) => i.id !== event.row.id,
                );
                this.toastService.success('Inventory item deleted');
              },
              error: () => this.toastService.error('Failed to delete inventory item'),
            });
          }
        });
    } else if (event.action === 'edit') {
      this.openEditDialog(event.row.id);
    }
  }

  private openEditDialog(itemId: string): void {
    const rawItem = this.rawItems.find((i) => i.id === itemId);
    if (!rawItem) return;

    const packageIdsWithShipments = new Set<string>(
      (rawItem.shipments || []).map((s: any) => s.packageId),
    );

    const item: InventoryItem = {
      id: rawItem.id,
      title: rawItem.title,
      ingredient: rawItem.ingredient,
      ingredientId: rawItem.ingredientId || rawItem.ingredient?.id,
      minStockLevel: rawItem.minStockLevel,
      minStockUnit: rawItem.minStockUnit,
      packages: (rawItem.packages || []).map((p: any) => ({
        ...p,
        hasShipments: packageIdsWithShipments.has(p.id),
      })),
    };

    const ref = this.dialog.open(AddInventoryDialogComponent, {
      data: { ingredients: this.ingredients, mode: 'edit', item },
      width: '500px',
    });
    ref.afterClosed().subscribe((result: AddInventoryDialogResult | undefined) => {
      if (result) {
        const { ingredientId, ...updatePayload } = result;
        this.apiClient.put(`/v1/inventory/${itemId}`, updatePayload).subscribe({
          next: () => {
            this.toastService.success('Inventory item updated');
            this.loadInventory();
          },
          error: () => this.toastService.error('Failed to update inventory item'),
        });
      }
    });
  }
}

// apps/admin-dashboard/src/pages/inventory.tsx
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router';
import {
  Package,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Eye,
  Truck,
  Trash2,
  Plus,
  X,
} from 'lucide-react';
import { toast } from 'sonner';
import {
  useInventoryItems,
  useDeleteInventoryItem,
  useCreateInventoryItem,
  useIngredients,
} from '@bake-app/react/api-client';
import {
  PageContainer,
  StatsCard,
  DataTable,
  LoadingSpinner,
  useConfirmation,
  type TableColumn,
} from '@bake-app/react/ui';
import type { InventoryItem } from '@bake-app/shared-types';

export function InventoryPage() {
  const navigate = useNavigate();
  const { data: items, isLoading } = useInventoryItems();
  const { data: ingredients } = useIngredients();
  const deleteItem = useDeleteInventoryItem();
  const createItem = useCreateInventoryItem();
  const { confirm, ConfirmationDialog } = useConfirmation();

  const [showAddDialog, setShowAddDialog] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({
    title: '',
    ingredientId: '',
    minStockLevel: 0,
    minStockUnit: 'g',
    packageSize: 1,
    packageUnit: 'kg',
  });

  const inventoryItems: InventoryItem[] = (items as InventoryItem[]) ?? [];

  const stats = useMemo(() => {
    const total = inventoryItems.length;
    const inStock = inventoryItems.filter(
      (i) => i.status === 'in_stock',
    ).length;
    const lowStock = inventoryItems.filter(
      (i) => i.status === 'low_stock',
    ).length;
    const outOfStock = inventoryItems.filter(
      (i) => i.status === 'out_of_stock',
    ).length;
    return { total, inStock, lowStock, outOfStock };
  }, [inventoryItems]);

  const handleDelete = async (item: InventoryItem) => {
    const ok = await confirm(
      'Delete Inventory Item',
      `Are you sure you want to delete "${item.title}"? This action cannot be undone.`,
      { variant: 'danger', confirmText: 'Delete' },
    );
    if (!ok) return;
    deleteItem.mutate(item.id, {
      onSuccess: () => toast.success('Item deleted'),
      onError: () => toast.error('Failed to delete item'),
    });
  };

  const handleCreate = () => {
    if (!form.title || !form.ingredientId) {
      toast.error('Please fill in all required fields');
      return;
    }
    setSaving(true);
    createItem.mutate(
      {
        title: form.title,
        ingredientId: form.ingredientId,
        minStockLevel: form.minStockLevel,
        minStockUnit: form.minStockUnit,
        packages: [
          { size: form.packageSize, unit: form.packageUnit } as any,
        ],
      } as any,
      {
        onSuccess: () => {
          toast.success('Inventory item created');
          setShowAddDialog(false);
          setForm({
            title: '',
            ingredientId: '',
            minStockLevel: 0,
            minStockUnit: 'g',
            packageSize: 1,
            packageUnit: 'kg',
          });
          setSaving(false);
        },
        onError: () => {
          toast.error('Failed to create item');
          setSaving(false);
        },
      },
    );
  };

  const columns: TableColumn[] = [
    {
      key: 'title',
      label: 'Item Title',
      sortable: true,
      render: (value: string) => (
        <span className="font-medium text-[#3e2723]">{value}</span>
      ),
    },
    {
      key: 'ingredient.name',
      label: 'Ingredient',
      sortable: true,
    },
    {
      key: 'quantity',
      label: 'Current Quantity',
      type: 'number',
      sortable: true,
      render: (value: number, row: InventoryItem) => (
        <span className="font-mono text-sm">
          {value?.toLocaleString() ?? 0} {row.metricUnit ?? ''}
        </span>
      ),
    },
    {
      key: 'status',
      label: 'Status',
      type: 'badge',
    },
    {
      key: 'minStockLevel',
      label: 'Min Stock Level',
      type: 'number',
      render: (value: number, row: InventoryItem) => (
        <span className="text-sm text-gray-600">
          {value ?? 0} {row.minStockUnit ?? ''}
        </span>
      ),
    },
    {
      key: 'actions',
      label: 'Actions',
      type: 'actions',
      actions: [
        {
          action: 'view',
          icon: <Eye size={16} />,
          tooltip: 'View details',
          onClick: (row: InventoryItem) => navigate(`/inventory/${row.id}`),
        },
        {
          action: 'shipment',
          icon: <Truck size={16} />,
          tooltip: 'Add shipment',
          onClick: (row: InventoryItem) => navigate(`/inventory/${row.id}`),
        },
        {
          action: 'delete',
          icon: <Trash2 size={16} />,
          color: 'text-red-500 hover:text-red-700',
          tooltip: 'Delete',
          onClick: (row: InventoryItem) => handleDelete(row),
        },
      ],
    },
  ];

  return (
    <PageContainer
      title="Inventory"
      subtitle="Manage inventory items, packages, and shipments"
      actions={
        <button
          type="button"
          onClick={() => setShowAddDialog(true)}
          className="flex items-center gap-2 rounded-lg bg-[#8b4513] px-4 py-2 text-sm font-medium text-white transition-all duration-150 hover:bg-[#5d4037] active:scale-95"
        >
          <Plus size={16} />
          Add Item
        </button>
      }
    >
      {/* Stats */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatsCard
          title="Total Items"
          value={stats.total}
          icon={<Package size={20} />}
        />
        <StatsCard
          title="In Stock"
          value={stats.inStock}
          icon={<CheckCircle2 size={20} />}
          color="success"
        />
        <StatsCard
          title="Low Stock"
          value={stats.lowStock}
          icon={<AlertTriangle size={20} />}
          color="warning"
        />
        <StatsCard
          title="Out of Stock"
          value={stats.outOfStock}
          icon={<XCircle size={20} />}
          color="danger"
        />
      </div>

      {/* Table */}
      {isLoading ? (
        <LoadingSpinner message="Loading inventory..." />
      ) : (
        <DataTable
          columns={columns}
          data={inventoryItems}
          onRowClick={(row) => navigate(`/inventory/${row.id}`)}
          searchable
          searchPlaceholder="Search inventory..."
          pageSize={10}
        />
      )}

      {ConfirmationDialog}

      {/* Add Item Dialog */}
      {showAddDialog && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm"
          onClick={() => setShowAddDialog(false)}
        >
          <div
            className="relative mx-4 w-full max-w-lg rounded-xl bg-white p-6 shadow-lg"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              type="button"
              onClick={() => setShowAddDialog(false)}
              className="absolute right-3 top-3 rounded-lg p-1 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600"
              aria-label="Close"
            >
              <X className="h-4 w-4" />
            </button>

            <h2 className="text-lg font-semibold text-[#3e2723]">
              Add Inventory Item
            </h2>

            <div className="mt-4 space-y-4">
              <div>
                <label className="mb-1 block text-sm font-medium text-gray-700">
                  Title *
                </label>
                <input
                  type="text"
                  value={form.title}
                  onChange={(e) =>
                    setForm({ ...form, title: e.target.value })
                  }
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-[#8b4513] focus:outline-none focus:ring-1 focus:ring-[#8b4513]/30"
                  placeholder="e.g. All-Purpose Flour"
                />
              </div>

              <div>
                <label className="mb-1 block text-sm font-medium text-gray-700">
                  Ingredient *
                </label>
                <select
                  value={form.ingredientId}
                  onChange={(e) =>
                    setForm({ ...form, ingredientId: e.target.value })
                  }
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-[#8b4513] focus:outline-none focus:ring-1 focus:ring-[#8b4513]/30"
                >
                  <option value="">Select ingredient</option>
                  {((ingredients as any[]) ?? []).map((ing: any) => (
                    <option key={ing.id} value={ing.id}>
                      {ing.name}
                    </option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="mb-1 block text-sm font-medium text-gray-700">
                    Min Stock Level
                  </label>
                  <input
                    type="number"
                    value={form.minStockLevel}
                    onChange={(e) =>
                      setForm({
                        ...form,
                        minStockLevel: Number(e.target.value),
                      })
                    }
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-[#8b4513] focus:outline-none focus:ring-1 focus:ring-[#8b4513]/30"
                    min="0"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium text-gray-700">
                    Min Stock Unit
                  </label>
                  <select
                    value={form.minStockUnit}
                    onChange={(e) =>
                      setForm({ ...form, minStockUnit: e.target.value })
                    }
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-[#8b4513] focus:outline-none focus:ring-1 focus:ring-[#8b4513]/30"
                  >
                    {['g', 'kg', 'ml', 'L', 'pcs'].map((u) => (
                      <option key={u} value={u}>
                        {u}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="border-t border-gray-100 pt-4">
                <p className="mb-3 text-sm font-medium text-gray-700">
                  Initial Package
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="mb-1 block text-xs text-gray-500">
                      Package Size
                    </label>
                    <input
                      type="number"
                      value={form.packageSize}
                      onChange={(e) =>
                        setForm({
                          ...form,
                          packageSize: Number(e.target.value),
                        })
                      }
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-[#8b4513] focus:outline-none focus:ring-1 focus:ring-[#8b4513]/30"
                      min="0"
                    />
                  </div>
                  <div>
                    <label className="mb-1 block text-xs text-gray-500">
                      Package Unit
                    </label>
                    <select
                      value={form.packageUnit}
                      onChange={(e) =>
                        setForm({ ...form, packageUnit: e.target.value })
                      }
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-[#8b4513] focus:outline-none focus:ring-1 focus:ring-[#8b4513]/30"
                    >
                      {['g', 'kg', 'lb', 'oz', 'ml', 'L', 'pcs'].map(
                        (u) => (
                          <option key={u} value={u}>
                            {u}
                          </option>
                        ),
                      )}
                    </select>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setShowAddDialog(false)}
                className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 transition-all duration-150 hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleCreate}
                disabled={saving}
                className="rounded-lg bg-[#8b4513] px-4 py-2 text-sm font-medium text-white transition-all duration-150 hover:bg-[#5d4037] active:scale-95 disabled:opacity-50"
              >
                {saving ? 'Creating...' : 'Add Item'}
              </button>
            </div>
          </div>
        </div>
      )}
    </PageContainer>
  );
}
