// apps/hub-app/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '@bake-app/auth';

@Component({
  selector: 'bake-app-login',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
  ],
  template: `
    <div class="login-container">
      <mat-card class="login-card">
        <div class="login-header">
          <mat-icon class="brand-icon">bakery_dining</mat-icon>
          <h1 class="brand-title">Bake App</h1>
          <p class="brand-subtitle">Sign in to access your workspace</p>
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="login-form">
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Email</mat-label>
            <input
              matInput
              type="email"
              formControlName="email"
              placeholder="your@email.com"
            />
            <mat-icon matPrefix>email</mat-icon>
            <mat-error *ngIf="loginForm.get('email')?.hasError('required')">
              Email is required
            </mat-error>
            <mat-error *ngIf="loginForm.get('email')?.hasError('email')">
              Please enter a valid email
            </mat-error>
          </mat-form-field>

          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Password</mat-label>
            <input
              matInput
              [type]="hidePassword ? 'password' : 'text'"
              formControlName="password"
              placeholder="Enter your password"
            />
            <mat-icon matPrefix>lock</mat-icon>
            <button
              mat-icon-button
              matSuffix
              type="button"
              (click)="hidePassword = !hidePassword"
            >
              <mat-icon>{{ hidePassword ? 'visibility_off' : 'visibility' }}</mat-icon>
            </button>
            <mat-error *ngIf="loginForm.get('password')?.hasError('required')">
              Password is required
            </mat-error>
          </mat-form-field>

          <div class="error-message" *ngIf="errorMessage">
            <mat-icon>error</mat-icon>
            {{ errorMessage }}
          </div>

          <button
            mat-flat-button
            class="sign-in-btn"
            type="submit"
            [disabled]="loginForm.invalid || isLoading"
          >
            <mat-spinner
              *ngIf="isLoading"
              diameter="20"
              class="btn-spinner"
            ></mat-spinner>
            <span *ngIf="!isLoading">Sign In</span>
          </button>
        </form>
      </mat-card>
    </div>
  `,
  styles: [
    `
      .login-container {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        background-color: #faf3e8;
        padding: 16px;
      }

      .login-card {
        width: 100%;
        max-width: 420px;
        padding: 40px 32px;
        border-radius: 12px;
        box-shadow: 0 8px 32px rgba(139, 69, 19, 0.12);
      }

      .login-header {
        text-align: center;
        margin-bottom: 32px;
      }

      .brand-icon {
        font-size: 56px;
        width: 56px;
        height: 56px;
        color: #8b4513;
        margin-bottom: 8px;
      }

      .brand-title {
        font-size: 28px;
        font-weight: 700;
        color: #8b4513;
        margin-bottom: 4px;
        font-family: 'Inter', sans-serif;
      }

      .brand-subtitle {
        font-size: 14px;
        color: #8d6e63;
        margin: 0;
      }

      .login-form {
        display: flex;
        flex-direction: column;
        gap: 4px;
      }

      .full-width {
        width: 100%;
      }

      .sign-in-btn {
        width: 100%;
        height: 48px;
        background-color: #8b4513 !important;
        color: #fff !important;
        font-size: 16px;
        font-weight: 600;
        border-radius: 8px;
        margin-top: 8px;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .sign-in-btn:disabled {
        opacity: 0.6;
      }

      .btn-spinner {
        display: inline-block;
      }

      .error-message {
        display: flex;
        align-items: center;
        gap: 8px;
        color: #c62828;
        font-size: 13px;
        padding: 8px 12px;
        background-color: #ffebee;
        border-radius: 6px;
        margin-bottom: 8px;
      }

      .error-message mat-icon {
        font-size: 18px;
        width: 18px;
        height: 18px;
      }
    `,
  ],
})
export class LoginComponent {
  loginForm: FormGroup;
  hidePassword = true;
  isLoading = false;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
    });
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';

    const { email, password } = this.loginForm.value;

    this.authService.login(email, password).subscribe({
      next: (response) => {
        this.authService.setToken(response.accessToken ?? '');
        this.isLoading = false;
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        this.isLoading = false;
        this.errorMessage =
          err.error?.message || 'Login failed. Please check your credentials.';
      },
    });
  }
}

// apps/admin-dashboard/src/pages/login.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router';
import { useAuth } from '@bake-app/react/auth';
import { Croissant, Mail, Lock, Eye, EyeOff, AlertCircle, Loader2 } from 'lucide-react';

export function LoginPage() {
  const { login, isAuthenticated } = useAuth();
  const navigate = useNavigate();

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [hidePassword, setHidePassword] = useState(true);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  useEffect(() => {
    if (isAuthenticated) {
      navigate('/dashboard', { replace: true });
    }
  }, [isAuthenticated, navigate]);

  const isFormValid = email.trim() !== '' && password.trim() !== '';

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!isFormValid || isLoading) return;

    setIsLoading(true);
    setErrorMessage('');

    try {
      await login(email, password);
    } catch (err) {
      setErrorMessage(
        err instanceof Error ? err.message : 'Login failed. Please check your credentials.',
      );
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="flex items-center justify-center min-h-screen bg-[#faf3e8] px-4">
      <div className="w-full max-w-[420px] bg-white rounded-xl p-10 shadow-[0_8px_32px_rgba(139,69,19,0.12)]">
        {/* Header */}
        <div className="text-center mb-8">
          <Croissant className="mx-auto mb-2 text-[#8b4513]" size={56} strokeWidth={1.5} />
          <h1 className="text-[28px] font-bold text-[#8b4513] mb-1 font-['Inter',sans-serif]">
            Bake App
          </h1>
          <p className="text-sm text-[#8d6e63] m-0">Admin Dashboard</p>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          {/* Email field */}
          <div>
            <label className="block text-sm font-medium text-[#5d4037] mb-1.5">Email</label>
            <div className="relative">
              <Mail
                className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8d6e63]"
                size={18}
              />
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="your@email.com"
                required
                className="w-full pl-10 pr-4 py-3 border border-[#d7ccc8] rounded-lg text-sm
                  text-[#3e2723] placeholder-[#bdbdbd] bg-white
                  focus:outline-none focus:border-[#8b4513] focus:ring-2 focus:ring-[#8b4513]/20
                  transition-colors"
              />
            </div>
          </div>

          {/* Password field */}
          <div>
            <label className="block text-sm font-medium text-[#5d4037] mb-1.5">Password</label>
            <div className="relative">
              <Lock
                className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8d6e63]"
                size={18}
              />
              <input
                type={hidePassword ? 'password' : 'text'}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Enter your password"
                required
                className="w-full pl-10 pr-11 py-3 border border-[#d7ccc8] rounded-lg text-sm
                  text-[#3e2723] placeholder-[#bdbdbd] bg-white
                  focus:outline-none focus:border-[#8b4513] focus:ring-2 focus:ring-[#8b4513]/20
                  transition-colors"
              />
              <button
                type="button"
                onClick={() => setHidePassword(!hidePassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-[#8d6e63]
                  hover:text-[#5d4037] bg-transparent border-none cursor-pointer p-0"
              >
                {hidePassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
          </div>

          {/* Error message */}
          {errorMessage && (
            <div className="flex items-center gap-2 text-[#c62828] text-[13px] px-3 py-2 bg-[#ffebee] rounded-md">
              <AlertCircle size={18} className="shrink-0" />
              {errorMessage}
            </div>
          )}

          {/* Submit button */}
          <button
            type="submit"
            disabled={!isFormValid || isLoading}
            className="w-full h-12 bg-[#8b4513] text-white text-base font-semibold rounded-lg
              mt-2 flex items-center justify-center cursor-pointer border-none
              hover:bg-[#7a3b10] transition-colors
              disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {isLoading ? <Loader2 size={20} className="animate-spin" /> : 'Sign In'}
          </button>
        </form>
      </div>
    </div>
  );
}
