// apps/pos-app/src/app/pages/order-detail/order-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { MatDividerModule } from '@angular/material/divider';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import {
  BakeStatusBadgeComponent,
  BakeCurrencyDisplayComponent,
} from '@bake-app/ui-components';
import { ApiClientService } from '@bake-app/api-client';
import { Order } from '@bake-app/shared-types';

interface OrderItemView {
  name: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

interface OrderDetailView {
  id: string;
  orderNumber: string;
  date: Date;
  status: string;
  paymentMethod: string;
  items: OrderItemView[];
  subtotal: number;
  tax: number;
  total: number;
  amountPaid: number;
  change: number;
  cashier: string;
}

@Component({
  selector: 'bake-app-order-detail',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatCardModule,
    MatDividerModule,
    MatProgressSpinnerModule,
    BakeStatusBadgeComponent,
    BakeCurrencyDisplayComponent,
  ],
  template: `
    <div class="order-detail-page" *ngIf="order">
      <div class="page-toolbar">
        <button mat-button class="back-btn" (click)="goBack()">
          <mat-icon>arrow_back</mat-icon>
          Back to Orders
        </button>
      </div>

      <div class="detail-layout">
        <!-- Order Info Card -->
        <mat-card class="info-card">
          <div class="card-header">
            <div class="order-id-section">
              <h1>Order {{ order.orderNumber }}</h1>
              <bake-status-badge [status]="order.status"></bake-status-badge>
            </div>
            <div class="order-meta">
              <span class="meta-item">
                <mat-icon>calendar_today</mat-icon>
                {{ order.date | date: 'medium' }}
              </span>
              <span class="meta-item">
                <mat-icon>person</mat-icon>
                {{ order.cashier }}
              </span>
              <span class="meta-item">
                <mat-icon>{{ order.paymentMethod === 'Cash' ? 'payments' : 'credit_card' }}</mat-icon>
                {{ order.paymentMethod }}
              </span>
            </div>
          </div>

          <mat-divider></mat-divider>

          <!-- Items table -->
          <div class="items-section">
            <h3>Items</h3>
            <table class="items-table">
              <thead>
                <tr>
                  <th class="col-item">Item</th>
                  <th class="col-qty">Qty</th>
                  <th class="col-price">Price</th>
                  <th class="col-total">Total</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let item of order.items">
                  <td class="col-item">{{ item.name }}</td>
                  <td class="col-qty">{{ item.quantity }}</td>
                  <td class="col-price">${{ item.unitPrice | number: '1.0-0' }}</td>
                  <td class="col-total">${{ item.total | number: '1.0-0' }}</td>
                </tr>
              </tbody>
            </table>
          </div>

          <mat-divider></mat-divider>

          <!-- Totals -->
          <div class="totals-section">
            <div class="total-line">
              <span>Subtotal</span>
              <span class="amount">${{ order.subtotal | number: '1.0-0' }}</span>
            </div>
            <div class="total-line tax">
              <span>Tax (12%)</span>
              <span class="amount">${{ order.tax | number: '1.0-0' }}</span>
            </div>
            <div class="total-line grand">
              <span>Total</span>
              <bake-currency-display
                [amount]="order.total"
                size="large"
              ></bake-currency-display>
            </div>
          </div>

          <mat-divider></mat-divider>

          <!-- Payment Info -->
          <div class="payment-section">
            <h3>Payment Details</h3>
            <div class="payment-grid">
              <div class="payment-item">
                <span class="payment-label">Method</span>
                <span class="payment-value">{{ order.paymentMethod }}</span>
              </div>
              <div class="payment-item">
                <span class="payment-label">Amount Paid</span>
                <span class="payment-value mono">
                  ${{ order.amountPaid | number: '1.0-0' }}
                </span>
              </div>
              <div class="payment-item" *ngIf="order.change > 0">
                <span class="payment-label">Change</span>
                <span class="payment-value mono change-value">
                  ${{ order.change | number: '1.0-0' }}
                </span>
              </div>
            </div>
          </div>
        </mat-card>
      </div>
    </div>

    <!-- Not found state -->
    <div class="not-found" *ngIf="!order && loaded">
      <mat-icon class="not-found-icon">search_off</mat-icon>
      <h2>Order not found</h2>
      <p>The order you are looking for does not exist.</p>
      <button mat-flat-button class="back-btn-primary" (click)="goBack()">
        <mat-icon>arrow_back</mat-icon>
        Back to Orders
      </button>
    </div>
  `,
  styles: [
    `
      .order-detail-page {
        padding: 24px;
        background-color: #faf3e8;
        min-height: calc(100vh - 64px);
      }

      .page-toolbar {
        margin-bottom: 16px;
      }

      .back-btn {
        color: #8b4513;
        font-weight: 500;
      }

      .detail-layout {
        max-width: 720px;
      }

      .info-card {
        border-radius: 12px;
        padding: 24px;
        box-shadow: 0 2px 12px rgba(139, 69, 19, 0.08);
      }

      .card-header {
        margin-bottom: 20px;
      }

      .order-id-section {
        display: flex;
        align-items: center;
        gap: 12px;
        margin-bottom: 12px;
      }

      .order-id-section h1 {
        font-size: 24px;
        font-weight: 700;
        color: #3e2723;
        margin: 0;
      }

      .order-meta {
        display: flex;
        gap: 20px;
        flex-wrap: wrap;
      }

      .meta-item {
        display: flex;
        align-items: center;
        gap: 6px;
        font-size: 13px;
        color: #8d6e63;
      }

      .meta-item mat-icon {
        font-size: 16px;
        width: 16px;
        height: 16px;
      }

      /* Items */
      .items-section {
        padding: 20px 0;
      }

      .items-section h3 {
        font-size: 16px;
        font-weight: 600;
        color: #3e2723;
        margin: 0 0 12px 0;
      }

      .items-table {
        width: 100%;
        border-collapse: collapse;
      }

      .items-table th {
        text-align: left;
        font-size: 12px;
        font-weight: 600;
        color: #8d6e63;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        padding: 8px 0;
        border-bottom: 1px solid #f0e6d8;
      }

      .items-table td {
        padding: 10px 0;
        font-size: 14px;
        color: #3e2723;
        border-bottom: 1px solid #f5efe8;
      }

      .col-qty {
        width: 60px;
        text-align: center;
      }

      .col-price,
      .col-total {
        width: 100px;
        text-align: right;
        font-family: 'JetBrains Mono', monospace;
        font-weight: 500;
      }

      .items-table th.col-qty {
        text-align: center;
      }

      .items-table th.col-price,
      .items-table th.col-total {
        text-align: right;
      }

      /* Totals */
      .totals-section {
        padding: 20px 0;
      }

      .total-line {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 4px 0;
        font-size: 14px;
        color: #5d4037;
      }

      .amount {
        font-family: 'JetBrains Mono', monospace;
        font-weight: 500;
      }

      .total-line.tax {
        font-size: 13px;
        color: #8d6e63;
        padding-bottom: 12px;
        margin-bottom: 8px;
        border-bottom: 1px dashed #e0d5c7;
      }

      .total-line.grand {
        font-size: 18px;
        font-weight: 700;
        color: #3e2723;
        padding-top: 8px;
      }

      /* Payment */
      .payment-section {
        padding: 20px 0 0;
      }

      .payment-section h3 {
        font-size: 16px;
        font-weight: 600;
        color: #3e2723;
        margin: 0 0 12px 0;
      }

      .payment-grid {
        display: flex;
        gap: 24px;
        flex-wrap: wrap;
      }

      .payment-item {
        display: flex;
        flex-direction: column;
        gap: 2px;
      }

      .payment-label {
        font-size: 12px;
        font-weight: 500;
        color: #8d6e63;
        text-transform: uppercase;
        letter-spacing: 0.3px;
      }

      .payment-value {
        font-size: 15px;
        font-weight: 600;
        color: #3e2723;
      }

      .payment-value.mono {
        font-family: 'JetBrains Mono', monospace;
      }

      .change-value {
        color: #2e7d32;
      }

      /* Not found */
      .not-found {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        min-height: calc(100vh - 64px);
        background-color: #faf3e8;
        color: #8d6e63;
      }

      .not-found-icon {
        font-size: 64px;
        width: 64px;
        height: 64px;
        margin-bottom: 16px;
      }

      .not-found h2 {
        margin: 0 0 8px 0;
        color: #5d4037;
      }

      .not-found p {
        margin: 0 0 24px 0;
      }

      .back-btn-primary {
        background-color: #8b4513 !important;
        color: #fff !important;
      }
    `,
  ],
})
export class OrderDetailComponent implements OnInit {
  order: OrderDetailView | null = null;
  loaded = false;
  loading = true;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiClient: ApiClientService,
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id') || '';
    this.apiClient.get<Order>(`/v1/orders/${id}`).subscribe({
      next: (apiOrder) => {
        const statusMap: Record<string, string> = {
          pending: 'Pending',
          confirmed: 'Confirmed',
          in_progress: 'In Progress',
          completed: 'Completed',
          cancelled: 'Cancelled',
        };
        const payment = apiOrder.payments?.[0];
        const amountPaid = apiOrder.payments?.reduce(
          (sum, p) => sum + p.amount,
          0,
        ) || 0;
        this.order = {
          id: apiOrder.id,
          orderNumber: apiOrder.orderNumber,
          date: new Date(apiOrder.createdAt),
          status: statusMap[apiOrder.status] || apiOrder.status,
          paymentMethod: payment?.method === 'cash' ? 'Cash' : 'Card',
          items: apiOrder.items.map((item) => ({
            name: item.product?.name || 'Item',
            quantity: item.quantity,
            unitPrice: item.unitPrice,
            total: item.subtotal,
          })),
          subtotal: apiOrder.subtotal,
          tax: apiOrder.tax,
          total: apiOrder.total,
          amountPaid,
          change: Math.max(0, amountPaid - apiOrder.total),
          cashier: apiOrder.userId || 'Unknown',
        };
        this.loaded = true;
        this.loading = false;
      },
      error: () => {
        this.order = null;
        this.loaded = true;
        this.loading = false;
      },
    });
  }

  goBack(): void {
    this.router.navigate(['/orders']);
  }
}

// apps/pos-app/src/pages/order-detail.tsx
import { useParams, useNavigate } from 'react-router';
import { ArrowLeft, Receipt, CreditCard, Banknote } from 'lucide-react';
import { useOrder } from '@bake-app/react/api-client';
import { CurrencyDisplay, StatusBadge, LoadingSpinner } from '@bake-app/react/ui';

export function OrderDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data: order, isLoading, error } = useOrder(id!);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-[#faf3e8] flex items-center justify-center">
        <LoadingSpinner message="Loading order..." />
      </div>
    );
  }

  if (error || !order) {
    return (
      <div className="min-h-screen bg-[#faf3e8] flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 font-medium mb-4">Failed to load order</p>
          <button
            type="button"
            onClick={() => navigate('/orders')}
            className="px-4 py-2 text-sm font-medium text-white bg-[#8b4513] rounded-lg
              border-none hover:bg-[#5d4037] transition-colors cursor-pointer"
          >
            Back to Orders
          </button>
        </div>
      </div>
    );
  }

  const payment = order.payments?.[0];

  return (
    <div className="min-h-screen bg-[#faf3e8]">
      {/* Header */}
      <div className="bg-white border-b border-[#8b4513]/10 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center gap-4">
          <button
            type="button"
            onClick={() => navigate('/orders')}
            className="flex items-center justify-center h-9 w-9 rounded-lg
              bg-[#faf3e8] text-[#5d4037] border border-[#8b4513]/10
              hover:bg-[#f5e6d0] transition-colors cursor-pointer"
          >
            <ArrowLeft size={18} />
          </button>
          <div className="flex items-center gap-3">
            <Receipt className="text-[#8b4513]" size={24} />
            <h1 className="text-xl font-bold text-[#3e2723]">
              Order <span className="font-mono">#{order.orderNumber}</span>
            </h1>
          </div>
          <div className="ml-auto">
            <StatusBadge status={order.status} />
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-6 space-y-6">
        {/* Order info */}
        <div className="bg-white rounded-xl border border-[#8b4513]/10 shadow-sm p-6">
          <div className="flex flex-wrap gap-6 text-sm">
            <div>
              <p className="text-gray-500 mb-1">Order Number</p>
              <p className="font-mono font-bold text-[#3e2723]">#{order.orderNumber}</p>
            </div>
            <div>
              <p className="text-gray-500 mb-1">Date</p>
              <p className="font-medium text-[#3e2723]">
                {new Date(order.createdAt).toLocaleString()}
              </p>
            </div>
            <div>
              <p className="text-gray-500 mb-1">Type</p>
              <p className="font-medium text-[#3e2723] capitalize">
                {order.type?.replace('_', ' ') ?? 'N/A'}
              </p>
            </div>
            <div>
              <p className="text-gray-500 mb-1">Status</p>
              <StatusBadge status={order.status} />
            </div>
          </div>
        </div>

        {/* Items table */}
        <div className="bg-white rounded-xl border border-[#8b4513]/10 shadow-sm overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-100">
            <h2 className="text-base font-bold text-[#3e2723]">Items</h2>
          </div>
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-gray-100 bg-[#faf3e8]/50">
                <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-[#5d4037]">
                  Product
                </th>
                <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-[#5d4037] text-center">
                  Qty
                </th>
                <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-[#5d4037] text-right">
                  Unit Price
                </th>
                <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-[#5d4037] text-right">
                  Subtotal
                </th>
              </tr>
            </thead>
            <tbody>
              {order.items?.map((item, idx) => (
                <tr
                  key={item.id}
                  className={`border-b border-gray-50 ${idx % 2 === 1 ? 'bg-gray-50/30' : ''}`}
                >
                  <td className="px-6 py-3 text-sm font-medium text-[#3e2723]">
                    {item.product?.name ?? `Product ${item.productId}`}
                  </td>
                  <td className="px-6 py-3 text-sm text-gray-700 text-center font-mono">
                    {item.quantity}
                  </td>
                  <td className="px-6 py-3 text-right">
                    <CurrencyDisplay amount={item.unitPrice} size="sm" />
                  </td>
                  <td className="px-6 py-3 text-right">
                    <CurrencyDisplay amount={item.subtotal} size="sm" />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Totals */}
          <div className="border-t border-gray-200 px-6 py-4 space-y-2">
            <div className="flex items-center justify-between text-sm text-[#5d4037]">
              <span>Subtotal</span>
              <CurrencyDisplay amount={order.subtotal} size="sm" />
            </div>
            <div className="flex items-center justify-between text-sm text-[#5d4037]">
              <span>Tax</span>
              <CurrencyDisplay amount={order.tax} size="sm" />
            </div>
            {order.discount > 0 && (
              <div className="flex items-center justify-between text-sm text-green-600">
                <span>Discount</span>
                <span className="font-mono font-semibold">-${order.discount.toFixed(2)}</span>
              </div>
            )}
            <div className="flex items-center justify-between pt-2 border-t border-gray-200">
              <span className="text-base font-bold text-[#3e2723]">Total</span>
              <CurrencyDisplay amount={order.total} size="lg" />
            </div>
          </div>
        </div>

        {/* Payment info */}
        {payment && (
          <div className="bg-white rounded-xl border border-[#8b4513]/10 shadow-sm p-6">
            <h2 className="text-base font-bold text-[#3e2723] mb-4">Payment</h2>
            <div className="flex flex-wrap gap-6 text-sm">
              <div className="flex items-center gap-2">
                {payment.method === 'cash' ? (
                  <Banknote size={20} className="text-green-600" />
                ) : (
                  <CreditCard size={20} className="text-blue-600" />
                )}
                <div>
                  <p className="text-gray-500 mb-0.5">Method</p>
                  <p className="font-medium text-[#3e2723] capitalize">{payment.method}</p>
                </div>
              </div>
              <div>
                <p className="text-gray-500 mb-0.5">Amount Paid</p>
                <CurrencyDisplay amount={payment.amount} size="md" />
              </div>
              {payment.method === 'cash' && payment.amount > order.total && (
                <div>
                  <p className="text-gray-500 mb-0.5">Change</p>
                  <span className="font-mono font-semibold text-green-700">
                    ${(payment.amount - order.total).toFixed(2)}
                  </span>
                </div>
              )}
              <div>
                <p className="text-gray-500 mb-0.5">Status</p>
                <StatusBadge status={payment.status} size="sm" />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
