// apps/pos-app/src/app/pages/pos/pos.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTabsModule } from '@angular/material/tabs';
import { MatBadgeModule } from '@angular/material/badge';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { BakeProductCardComponent, BakeCurrencyDisplayComponent } from '@bake-app/ui-components';
import { ApiClientService } from '@bake-app/api-client';
import { Product as SharedProduct, Category as SharedCategory } from '@bake-app/shared-types';
import {
  PaymentDialogComponent,
  PaymentDialogData,
  PaymentDialogResult,
} from './payment-dialog.component';

interface PosProduct {
  id: string;
  name: string;
  price: number;
  category: string;
}

interface CartItem {
  product: PosProduct;
  quantity: number;
}

interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

@Component({
  selector: 'bake-app-pos',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatTabsModule,
    MatBadgeModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    BakeProductCardComponent,
    BakeCurrencyDisplayComponent,
  ],
  template: `
    <div class="pos-layout">
      <!-- Left Panel: Product Selection -->
      <div class="products-panel">
        <div class="loading-overlay" *ngIf="loading">
          <mat-spinner diameter="48"></mat-spinner>
          <p>Loading products...</p>
        </div>

        <div class="error-banner" *ngIf="errorMessage">
          <mat-icon>error</mat-icon>
          <span>{{ errorMessage }}</span>
          <button mat-button (click)="loadData()">Retry</button>
        </div>

        <mat-tab-group
          *ngIf="!loading"
          class="category-tabs"
          [(selectedIndex)]="selectedCategoryIndex"
          animationDuration="150ms"
        >
          <mat-tab *ngFor="let category of categories">
            <ng-template mat-tab-label>
              <mat-icon>{{ getCategoryIcon(category) }}</mat-icon>
              <span class="category-label">{{ category }}</span>
            </ng-template>
          </mat-tab>
        </mat-tab-group>

        <div class="product-grid" *ngIf="!loading">
          <bake-product-card
            *ngFor="let product of filteredProducts"
            [name]="product.name"
            [price]="product.price"
            [category]="product.category"
            (addToCart)="addToCart(product)"
          ></bake-product-card>
        </div>
      </div>

      <!-- Right Panel: Cart -->
      <div class="cart-panel">
        <div class="cart-header">
          <mat-icon>shopping_cart</mat-icon>
          <h2>Current Order</h2>
          <span class="item-count" *ngIf="cart.length > 0">
            {{ totalItems }} item{{ totalItems !== 1 ? 's' : '' }}
          </span>
        </div>

        <!-- Empty cart -->
        <div class="cart-empty" *ngIf="cart.length === 0">
          <mat-icon class="empty-icon">add_shopping_cart</mat-icon>
          <p>No items yet</p>
          <p class="empty-hint">Tap a product to add it</p>
        </div>

        <!-- Cart items -->
        <div class="cart-items" *ngIf="cart.length > 0">
          <div class="cart-item" *ngFor="let item of cart; let i = index">
            <div class="item-info">
              <span class="item-name">{{ item.product.name }}</span>
              <span class="item-price">
                {{ item.product.price * item.quantity | currency:'USD':'symbol':'1.0-0' }}
              </span>
            </div>
            <div class="item-controls">
              <button
                mat-icon-button
                class="qty-btn"
                (click)="decrementItem(i)"
              >
                <mat-icon>{{ item.quantity === 1 ? 'delete' : 'remove' }}</mat-icon>
              </button>
              <span class="qty-value">{{ item.quantity }}</span>
              <button
                mat-icon-button
                class="qty-btn"
                (click)="incrementItem(i)"
              >
                <mat-icon>add</mat-icon>
              </button>
            </div>
          </div>
        </div>

        <!-- Cart totals -->
        <div class="cart-totals" *ngIf="cart.length > 0">
          <div class="total-row">
            <span>Subtotal</span>
            <span class="total-value">{{ subtotal | currency:'USD':'symbol':'1.0-0' }}</span>
          </div>
          <div class="total-row tax-row">
            <span>Tax (12%)</span>
            <span class="total-value">{{ tax | currency:'USD':'symbol':'1.0-0' }}</span>
          </div>
          <div class="total-row grand-total">
            <span>Total</span>
            <bake-currency-display
              [amount]="total"
              size="large"
            ></bake-currency-display>
          </div>
        </div>

        <!-- Action buttons -->
        <div class="cart-actions" *ngIf="cart.length > 0">
          <button mat-stroked-button class="clear-btn" (click)="clearCart()">
            <mat-icon>delete_sweep</mat-icon>
            Clear
          </button>
          <button mat-flat-button class="pay-btn" (click)="openPaymentDialog()">
            <mat-icon>payment</mat-icon>
            PAY {{ total | currency:'USD':'symbol':'1.0-0' }}
          </button>
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .pos-layout {
        display: flex;
        height: calc(100vh - 64px);
        background-color: #faf3e8;
      }

      /* --- Left Panel --- */
      .products-panel {
        flex: 6;
        display: flex;
        flex-direction: column;
        overflow: hidden;
        border-right: 1px solid #e0d5c7;
      }

      .category-tabs {
        flex-shrink: 0;
        background-color: #fff;
        border-bottom: 1px solid #e0d5c7;
      }

      .category-label {
        margin-left: 6px;
        font-size: 13px;
      }

      .product-grid {
        flex: 1;
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
        gap: 12px;
        padding: 16px;
        overflow-y: auto;
        align-content: start;
      }

      /* --- Right Panel --- */
      .cart-panel {
        flex: 4;
        display: flex;
        flex-direction: column;
        background-color: #fff;
        min-width: 340px;
        max-width: 440px;
      }

      .cart-header {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 16px 20px;
        border-bottom: 1px solid #f0e6d8;
        color: #3e2723;
      }

      .cart-header h2 {
        margin: 0;
        font-size: 18px;
        font-weight: 600;
      }

      .item-count {
        margin-left: auto;
        font-size: 13px;
        color: #8d6e63;
        background-color: #faf3e8;
        padding: 2px 10px;
        border-radius: 12px;
      }

      /* Empty state */
      .cart-empty {
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        color: #bcaaa4;
      }

      .empty-icon {
        font-size: 64px;
        width: 64px;
        height: 64px;
        margin-bottom: 12px;
      }

      .cart-empty p {
        margin: 0;
        font-size: 16px;
        font-weight: 500;
      }

      .empty-hint {
        font-size: 13px !important;
        font-weight: 400 !important;
        margin-top: 4px !important;
      }

      /* Cart items */
      .cart-items {
        flex: 1;
        overflow-y: auto;
        padding: 8px 0;
      }

      .cart-item {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 8px 20px;
        border-bottom: 1px solid #f5efe8;
        transition: background-color 0.15s;
      }

      .cart-item:hover {
        background-color: #faf8f5;
      }

      .item-info {
        display: flex;
        flex-direction: column;
        gap: 2px;
        flex: 1;
        min-width: 0;
      }

      .item-name {
        font-size: 14px;
        font-weight: 500;
        color: #3e2723;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      .item-price {
        font-size: 13px;
        font-family: 'JetBrains Mono', monospace;
        font-weight: 500;
        color: #8b4513;
      }

      .item-controls {
        display: flex;
        align-items: center;
        gap: 4px;
        flex-shrink: 0;
      }

      .qty-btn {
        width: 32px;
        height: 32px;
        color: #5d4037;
      }

      .qty-btn mat-icon {
        font-size: 18px;
      }

      .qty-value {
        min-width: 28px;
        text-align: center;
        font-size: 15px;
        font-weight: 600;
        font-family: 'JetBrains Mono', monospace;
        color: #3e2723;
      }

      /* Totals */
      .cart-totals {
        padding: 16px 20px;
        border-top: 2px solid #f0e6d8;
        background-color: #fdfbf8;
      }

      .total-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 4px 0;
        font-size: 14px;
        color: #5d4037;
      }

      .total-value {
        font-family: 'JetBrains Mono', monospace;
        font-weight: 500;
      }

      .tax-row {
        font-size: 13px;
        color: #8d6e63;
        padding-bottom: 12px;
        border-bottom: 1px dashed #e0d5c7;
        margin-bottom: 8px;
      }

      .grand-total {
        font-size: 18px;
        font-weight: 700;
        color: #3e2723;
        padding-top: 8px;
      }

      /* Actions */
      .cart-actions {
        display: flex;
        gap: 12px;
        padding: 16px 20px;
        border-top: 1px solid #f0e6d8;
      }

      .clear-btn {
        flex-shrink: 0;
        color: #8d6e63;
        border-color: #d4a574;
      }

      .pay-btn {
        flex: 1;
        height: 52px;
        font-size: 16px;
        font-weight: 700;
        font-family: 'JetBrains Mono', monospace;
        background-color: #2e7d32 !important;
        color: #fff !important;
        border-radius: 10px;
        letter-spacing: 0.5px;
      }

      .pay-btn mat-icon {
        margin-right: 4px;
      }

      .loading-overlay {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        flex: 1;
        gap: 16px;
        color: #8d6e63;
      }

      .error-banner {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 12px 16px;
        background-color: #ffebee;
        color: #c62828;
        font-size: 13px;
      }

      .error-banner mat-icon {
        font-size: 18px;
        width: 18px;
        height: 18px;
      }
    `,
  ],
})
export class PosComponent implements OnInit {
  categories: string[] = [];
  products: PosProduct[] = [];
  cart: CartItem[] = [];
  selectedCategoryIndex = 0;
  loading = true;
  errorMessage = '';

  constructor(
    private dialog: MatDialog,
    private snackBar: MatSnackBar,
    private apiClient: ApiClientService,
  ) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.loading = true;
    this.errorMessage = '';

    this.apiClient.get<SharedCategory[]>('/v1/categories').subscribe({
      next: (cats) => {
        this.categories = cats.map((c) => c.name);
        this.loadProducts();
      },
      error: () => {
        this.categories = [];
        this.loadProducts();
      },
    });
  }

  private loadProducts(): void {
    this.apiClient
      .get<PaginatedResponse<SharedProduct>>('/v1/products?limit=100')
      .subscribe({
        next: (response) => {
          this.products = response.data.map((p) => ({
            id: p.id,
            name: p.name,
            price: p.price,
            category: p.category?.name || 'Other',
          }));
          if (this.categories.length === 0) {
            this.categories = [...new Set(this.products.map((p) => p.category))];
          }
          this.loading = false;
        },
        error: (err) => {
          this.errorMessage =
            'Failed to load products. Please check your connection and try again.';
          this.loading = false;
        },
      });
  }

  get selectedCategory(): string {
    return this.categories[this.selectedCategoryIndex];
  }

  get filteredProducts(): PosProduct[] {
    return this.products.filter((p) => p.category === this.selectedCategory);
  }

  get totalItems(): number {
    return this.cart.reduce((sum, item) => sum + item.quantity, 0);
  }

  get subtotal(): number {
    return this.cart.reduce(
      (sum, item) => sum + item.product.price * item.quantity,
      0
    );
  }

  get tax(): number {
    return Math.round(this.subtotal * 0.12);
  }

  get total(): number {
    return this.subtotal + this.tax;
  }

  getCategoryIcon(category: string): string {
    const icons: Record<string, string> = {
      Coffee: 'coffee',
      Pastries: 'bakery_dining',
      Bread: 'breakfast_dining',
      Sandwiches: 'lunch_dining',
      Drinks: 'local_bar',
      Desserts: 'cake',
    };
    return icons[category] || 'restaurant';
  }

  addToCart(product: PosProduct): void {
    const existingIndex = this.cart.findIndex(
      (item) => item.product.id === product.id
    );
    if (existingIndex >= 0) {
      this.cart[existingIndex] = {
        ...this.cart[existingIndex],
        quantity: this.cart[existingIndex].quantity + 1,
      };
    } else {
      this.cart = [...this.cart, { product, quantity: 1 }];
    }
  }

  incrementItem(index: number): void {
    this.cart[index] = {
      ...this.cart[index],
      quantity: this.cart[index].quantity + 1,
    };
  }

  decrementItem(index: number): void {
    if (this.cart[index].quantity <= 1) {
      this.removeItem(index);
    } else {
      this.cart[index] = {
        ...this.cart[index],
        quantity: this.cart[index].quantity - 1,
      };
    }
  }

  removeItem(index: number): void {
    this.cart = this.cart.filter((_, i) => i !== index);
  }

  clearCart(): void {
    this.cart = [];
  }

  openPaymentDialog(): void {
    const dialogData: PaymentDialogData = {
      total: this.total,
      itemCount: this.totalItems,
    };

    const dialogRef = this.dialog.open(PaymentDialogComponent, {
      width: '480px',
      disableClose: true,
      data: dialogData,
    });

    dialogRef.afterClosed().subscribe((result: PaymentDialogResult | undefined) => {
      if (!result) return;

      const orderPayload = {
        type: 'dine_in',
        items: this.cart.map((item) => ({
          productId: item.product.id,
          quantity: item.quantity,
          unitPrice: item.product.price,
        })),
      };

      this.apiClient.post<{ id: string }>('/v1/orders', orderPayload).subscribe({
        next: (order) => {
          const paymentPayload = {
            amount: result.amountPaid,
            method: result.method,
            status: 'completed',
          };

          this.apiClient
            .post(`/v1/orders/${order.id}/payments`, paymentPayload)
            .subscribe({
              next: () => {
                this.apiClient
                  .put(`/v1/orders/${order.id}/status`, { status: 'confirmed' })
                  .subscribe({
                    next: () => {
                      this.cart = [];
                      this.snackBar.open(
                        `Payment successful! ${result.method === 'cash' ? 'Change: $' + result.change : 'Card approved.'}`,
                        'OK',
                        {
                          duration: 4000,
                          horizontalPosition: 'center',
                          verticalPosition: 'top',
                        }
                      );
                    },
                    error: () => {
                      this.cart = [];
                      this.snackBar.open(
                        'Order placed but status update failed.',
                        'OK',
                        { duration: 4000 }
                      );
                    },
                  });
              },
              error: () => {
                this.snackBar.open(
                  'Order created but payment recording failed. Please retry.',
                  'OK',
                  { duration: 5000 }
                );
              },
            });
        },
        error: () => {
          this.snackBar.open(
            'Failed to create order. Please try again.',
            'OK',
            { duration: 5000 }
          );
        },
      });
    });
  }
}

// apps/pos-app/src/pages/pos.tsx
import { useState, useMemo } from 'react';
import {
  ShoppingCart,
  Trash2,
  Plus,
  Minus,
  ShoppingBag,
  Coffee,
  Croissant,
  Wheat,
  Cake,
  IceCreamCone,
  Cookie,
  Sandwich,
  UtensilsCrossed,
  RefreshCw,
  ClipboardList,
  LogOut,
} from 'lucide-react';
import { toast } from 'sonner';
import { useNavigate } from 'react-router';
import { useCategories, useProducts, useCreateOrder, useCreatePayment, useUpdateOrderStatus } from '@bake-app/react/api-client';
import { ProductCard, CurrencyDisplay, LoadingSpinner } from '@bake-app/react/ui';
import { useCartStore, selectSubtotal, selectTax, selectTotal, selectTotalItems } from '@bake-app/react/store';
import { useAuth } from '@bake-app/react/auth';
import { PaymentDialog, type PaymentResult } from '../components/payment-dialog';

const categoryIconMap: Record<string, React.ReactNode> = {
  coffee: <Coffee size={16} />,
  pastries: <Croissant size={16} />,
  bread: <Wheat size={16} />,
  cakes: <Cake size={16} />,
  desserts: <IceCreamCone size={16} />,
  cookies: <Cookie size={16} />,
  sandwiches: <Sandwich size={16} />,
};

function getCategoryIcon(name: string): React.ReactNode {
  const key = name.toLowerCase();
  return categoryIconMap[key] ?? <UtensilsCrossed size={16} />;
}

export function PosPage() {
  const navigate = useNavigate();
  const { logout } = useAuth();
  const [selectedCategoryIndex, setSelectedCategoryIndex] = useState(0);
  const [paymentOpen, setPaymentOpen] = useState(false);
  const [processing, setProcessing] = useState(false);

  // Data
  const { data: categories, isLoading: categoriesLoading, error: categoriesError, refetch: refetchCategories } = useCategories();
  const { data: productsResponse, isLoading: productsLoading, error: productsError, refetch: refetchProducts } = useProducts({ limit: 100 });

  // Mutations
  const createOrder = useCreateOrder();
  const createPayment = useCreatePayment();
  const updateStatus = useUpdateOrderStatus();

  // Cart
  const items = useCartStore((s) => s.items);
  const addItem = useCartStore((s) => s.addItem);
  const incrementItem = useCartStore((s) => s.incrementItem);
  const decrementItem = useCartStore((s) => s.decrementItem);
  const clearCart = useCartStore((s) => s.clear);
  const subtotal = useCartStore(selectSubtotal);
  const tax = useCartStore(selectTax);
  const total = useCartStore(selectTotal);
  const totalItems = useCartStore(selectTotalItems);

  // Filtered products
  const products = productsResponse?.data ?? [];
  const activeCategories = categories ?? [];

  const filteredProducts = useMemo(() => {
    if (activeCategories.length === 0) return products;
    // Index 0 = "All"
    if (selectedCategoryIndex === 0) return products;
    const cat = activeCategories[selectedCategoryIndex - 1];
    if (!cat) return products;
    return products.filter((p) => p.categoryId === cat.id);
  }, [products, activeCategories, selectedCategoryIndex]);

  const isLoading = categoriesLoading || productsLoading;
  const hasError = categoriesError || productsError;

  // Payment flow
  async function handlePayment(result: PaymentResult) {
    setProcessing(true);
    try {
      // 1. Create order
      const orderItems = items.map((item) => ({
        productId: item.product.id,
        quantity: item.quantity,
        unitPrice: item.product.price,
        subtotal: item.product.price * item.quantity,
      }));

      const order = await createOrder.mutateAsync({
        type: 'dine_in',
        status: 'pending',
        items: orderItems,
        subtotal,
        tax,
        total,
        discount: 0,
      } as any);

      // 2. Create payment
      await createPayment.mutateAsync({
        orderId: order.id,
        method: result.method,
        amount: result.amountPaid,
        status: 'completed',
      });

      // 3. Update order status
      await updateStatus.mutateAsync({ id: order.id, status: 'confirmed' });

      // 4. Clear cart
      clearCart();

      // 5. Success toast
      const changeMsg =
        result.method === 'cash' && result.change > 0
          ? ` | Change: $${result.change.toFixed(2)}`
          : '';
      toast.success(`Order #${order.orderNumber} completed!${changeMsg}`);
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : 'Payment failed. Please try again.',
      );
    } finally {
      setProcessing(false);
    }
  }

  function handleRetry() {
    refetchCategories();
    refetchProducts();
  }

  return (
    <div className="flex h-screen bg-[#faf3e8]">
      {/* Left panel — Products */}
      <div className="flex flex-[6] flex-col overflow-hidden">
        {/* Top bar */}
        <div className="flex items-center justify-between px-6 py-4 bg-white border-b border-[#8b4513]/10">
          <div className="flex items-center gap-3">
            <Croissant className="text-[#8b4513]" size={28} strokeWidth={1.5} />
            <h1 className="text-xl font-bold text-[#3e2723]">Bake POS</h1>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => navigate('/orders')}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium text-[#5d4037]
                bg-[#faf3e8] rounded-lg border border-[#8b4513]/10 hover:bg-[#f5e6d0]
                transition-colors cursor-pointer"
            >
              <ClipboardList size={16} />
              Orders
            </button>
            <button
              type="button"
              onClick={logout}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium text-[#5d4037]
                bg-[#faf3e8] rounded-lg border border-[#8b4513]/10 hover:bg-[#f5e6d0]
                transition-colors cursor-pointer"
            >
              <LogOut size={16} />
            </button>
          </div>
        </div>

        {/* Category tabs */}
        <div className="flex gap-2 px-6 py-3 overflow-x-auto bg-white border-b border-[#8b4513]/10 scrollbar-none">
          <button
            type="button"
            onClick={() => setSelectedCategoryIndex(0)}
            className={`shrink-0 flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-full
              border transition-colors cursor-pointer ${
                selectedCategoryIndex === 0
                  ? 'bg-[#8b4513] text-white border-[#8b4513]'
                  : 'bg-white text-[#5d4037] border-[#8b4513]/15 hover:bg-[#faf3e8]'
              }`}
          >
            <UtensilsCrossed size={16} />
            All
          </button>
          {activeCategories.map((cat, idx) => (
            <button
              key={cat.id}
              type="button"
              onClick={() => setSelectedCategoryIndex(idx + 1)}
              className={`shrink-0 flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-full
                border transition-colors cursor-pointer ${
                  selectedCategoryIndex === idx + 1
                    ? 'bg-[#8b4513] text-white border-[#8b4513]'
                    : 'bg-white text-[#5d4037] border-[#8b4513]/15 hover:bg-[#faf3e8]'
                }`}
            >
              {getCategoryIcon(cat.name)}
              {cat.name}
            </button>
          ))}
        </div>

        {/* Products grid */}
        <div className="flex-1 overflow-y-auto p-6">
          {isLoading ? (
            <LoadingSpinner message="Loading products..." />
          ) : hasError ? (
            <div className="flex flex-col items-center justify-center py-20 gap-4">
              <p className="text-red-600 text-sm font-medium">Failed to load products</p>
              <button
                type="button"
                onClick={handleRetry}
                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white
                  bg-[#8b4513] rounded-lg border-none hover:bg-[#5d4037] transition-colors cursor-pointer"
              >
                <RefreshCw size={16} />
                Retry
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-[repeat(auto-fill,minmax(150px,1fr))] gap-3">
              {filteredProducts.map((product) => (
                <ProductCard
                  key={product.id}
                  name={product.name}
                  price={product.price}
                  category={product.category?.name}
                  onAddToCart={() =>
                    addItem({
                      id: product.id,
                      name: product.name,
                      price: product.price,
                      category: product.category?.name ?? '',
                    })
                  }
                />
              ))}
              {filteredProducts.length === 0 && !isLoading && (
                <div className="col-span-full text-center py-12 text-gray-500">
                  <p className="text-sm">No products in this category</p>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Right panel — Cart */}
      <div className="flex flex-col flex-[4] min-w-[340px] max-w-[440px] bg-white border-l border-[#8b4513]/10">
        {/* Cart header */}
        <div className="flex items-center gap-3 px-6 py-4 border-b border-[#8b4513]/10">
          <ShoppingCart className="text-[#8b4513]" size={22} />
          <h2 className="text-lg font-bold text-[#3e2723]">Current Order</h2>
          {totalItems > 0 && (
            <span className="ml-auto flex h-6 min-w-6 items-center justify-center rounded-full bg-[#8b4513] px-2 text-xs font-bold text-white">
              {totalItems}
            </span>
          )}
        </div>

        {/* Cart items */}
        <div className="flex-1 overflow-y-auto px-6 py-4">
          {items.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full gap-3 text-gray-400">
              <ShoppingBag size={48} strokeWidth={1} />
              <p className="text-base font-medium text-gray-500">No items yet</p>
              <p className="text-sm text-gray-400">Tap a product to add it</p>
            </div>
          ) : (
            <div className="space-y-3">
              {items.map((item, idx) => (
                <div
                  key={item.product.id}
                  className="flex items-center gap-3 p-3 rounded-xl bg-[#faf3e8]/60 border border-[#8b4513]/5"
                >
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-[#3e2723] truncate">
                      {item.product.name}
                    </p>
                    <p className="text-sm font-mono text-[#5d4037]">
                      ${item.product.price.toFixed(2)}
                    </p>
                  </div>

                  {/* Quantity controls */}
                  <div className="flex items-center gap-1">
                    <button
                      type="button"
                      onClick={() => decrementItem(idx)}
                      className={`flex h-7 w-7 items-center justify-center rounded-lg border-none
                        cursor-pointer transition-colors ${
                          item.quantity <= 1
                            ? 'bg-red-100 text-red-600 hover:bg-red-200'
                            : 'bg-[#8b4513]/10 text-[#5d4037] hover:bg-[#8b4513]/20'
                        }`}
                      aria-label={item.quantity <= 1 ? 'Remove item' : 'Decrease quantity'}
                    >
                      {item.quantity <= 1 ? <Trash2 size={14} /> : <Minus size={14} />}
                    </button>
                    <span className="w-8 text-center text-sm font-bold text-[#3e2723]">
                      {item.quantity}
                    </span>
                    <button
                      type="button"
                      onClick={() => incrementItem(idx)}
                      className="flex h-7 w-7 items-center justify-center rounded-lg
                        bg-[#8b4513]/10 text-[#5d4037] hover:bg-[#8b4513]/20
                        border-none cursor-pointer transition-colors"
                      aria-label="Increase quantity"
                    >
                      <Plus size={14} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Totals and actions */}
        {items.length > 0 && (
          <div className="border-t border-[#8b4513]/10 px-6 py-4 space-y-3">
            {/* Totals */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-sm text-[#5d4037]">
                <span>Subtotal</span>
                <CurrencyDisplay amount={subtotal} size="sm" />
              </div>
              <div className="flex items-center justify-between text-sm text-[#5d4037]">
                <span>Tax (12%)</span>
                <CurrencyDisplay amount={tax} size="sm" />
              </div>
              <div className="flex items-center justify-between pt-2 border-t border-[#8b4513]/10">
                <span className="text-base font-bold text-[#3e2723]">Grand Total</span>
                <CurrencyDisplay amount={total} size="lg" />
              </div>
            </div>

            {/* Action buttons */}
            <div className="flex gap-2">
              <button
                type="button"
                onClick={clearCart}
                className="flex-1 py-3 text-sm font-semibold text-[#8b4513] bg-white
                  border-2 border-[#8b4513]/30 rounded-xl hover:bg-[#faf3e8]
                  transition-colors cursor-pointer"
              >
                Clear
              </button>
              <button
                type="button"
                onClick={() => setPaymentOpen(true)}
                disabled={processing}
                className="flex-[2] py-3 text-base font-bold text-white bg-green-600
                  rounded-xl border-none hover:bg-green-700 transition-colors cursor-pointer
                  disabled:opacity-50 disabled:cursor-not-allowed"
              >
                PAY ${total.toFixed(2)}
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Payment dialog */}
      <PaymentDialog
        open={paymentOpen}
        onClose={() => setPaymentOpen(false)}
        total={total}
        itemCount={totalItems}
        onConfirm={handlePayment}
      />
    </div>
  );
}
